{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper"]]},"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyShaderProgram","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","externalID":"c:@N@Overlay@S@HgiWrapper@F@DestroyShaderProgram#*$@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiShaderProgram#","symbolKind":"method","title":"DestroyShaderProgram(_:)","role":"symbol","modules":[{"name":"OpenUSD"}],"fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DestroyShaderProgram","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiShaderProgram","text":"HgiShaderProgramHandle","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"DestroyShaderProgram","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"DestroyShaderProgram"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"shaderProgramHandle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiShaderProgram","kind":"typeIdentifier","text":"HgiShaderProgramHandle"},{"kind":"text","text":">"},{"kind":"text","text":")"}],"platforms":["macOS"],"languages":["swift"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/openusd\/overlay\/hgiwrapper\/destroyshaderprogram"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/hgiwrapper\/destroyshaderprogram"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"role":"symbol","abstract":[{"type":"text","text":"The namespace used to group workarounds to limitations in Swift-Cxx interop"}],"url":"\/documentation\/openusd\/overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","type":"topic","fragments":[{"text":"Overlay","kind":"identifier"}],"title":"Overlay","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiWrapper","kind":"identifier"}],"title":"class HgiWrapper","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","navigatorTitle":[{"text":"HgiWrapper","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/hgiwrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/DestroyShaderProgram":{"abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"DestroyShaderProgram"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiShaderProgram","kind":"typeIdentifier","text":"HgiShaderProgramHandle"},{"kind":"text","text":">"},{"kind":"text","text":")"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/DestroyShaderProgram","title":"DestroyShaderProgram(_:)","navigatorTitle":[{"text":"DestroyShaderProgram","kind":"identifier"}],"url":"\/documentation\/openusd\/overlay\/hgiwrapper\/destroyshaderprogram"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"DestroyShaderProgram"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DestroyShaderProgram"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DestroyShaderProgram","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" "},{"kind":"identifier","text":"DestroyShaderProgram"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiShaderProgram","text":"HgiShaderProgramHandle"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"shaderProgramHandle"},{"kind":"text","text":");"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}]},{"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"text":"Overlay","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/title","value":"HgiWrapper"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/fragments","value":[{"text":"HgiWrapper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/navigatorTitle","value":[{"text":"HgiWrapper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyShaderProgram\/title","value":"DestroyShaderProgram"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyShaderProgram\/fragments","value":[{"text":"DestroyShaderProgram","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1DestroyShaderProgram\/navigatorTitle","value":[{"text":"DestroyShaderProgram","kind":"identifier"}]}]}]}