{"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/WriteMode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Replace","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}]}],"kind":"symbol","sections":[],"metadata":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Replace","kind":"identifier"}],"externalID":"c:@N@Overlay@S@ArResolverWrapper@E@WriteMode@Replace","roleHeading":"Enumeration Case","navigatorTitle":[{"text":"Replace","kind":"identifier"}],"title":"Replace","modules":[{"name":"OpenUSD"}],"symbolKind":"case"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/arresolverwrapper\/writemode\/replace"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/arresolverwrapper\/writemode\/replace"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/WriteMode\/Replace"},"references":{"doc://SwiftUsd/documentation/OpenUSD":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol","title":"OpenUSD","type":"topic","role":"collection","url":"\/documentation\/openusd"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"text":"Overlay","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","title":"Overlay","url":"\/documentation\/openusd\/overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper":{"title":"class ArResolverWrapper","type":"topic","navigatorTitle":[{"text":"ArResolverWrapper","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","abstract":[],"role":"symbol","url":"\/documentation\/openusd\/overlay\/arresolverwrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ArResolverWrapper","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/WriteMode/Replace":{"navigatorTitle":[{"text":"Replace","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Replace","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/WriteMode\/Replace","abstract":[],"title":"Replace","role":"symbol","type":"topic","url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/writemode\/replace"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/WriteMode":{"kind":"symbol","abstract":[],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WriteMode","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/WriteMode","url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/writemode","navigatorTitle":[{"text":"WriteMode","kind":"identifier"}],"title":"WriteMode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"Replace","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"Replace","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"Replace","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"Replace"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","op":"replace"},{"value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","op":"replace"},{"value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","op":"add"},{"value":"ArResolverWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ArResolverWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/fragments","op":"replace"},{"value":[{"text":"ArResolverWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/navigatorTitle","op":"replace"},{"value":"Replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1WriteMode~1Replace\/title","op":"replace"},{"value":[{"text":"Replace","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1WriteMode~1Replace\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Replace"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1WriteMode~1Replace\/navigatorTitle","op":"replace"},{"value":"WriteMode","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1WriteMode\/title","op":"replace"},{"value":[{"text":"WriteMode","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1WriteMode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"WriteMode"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1WriteMode\/navigatorTitle","op":"replace"}]}]}