{"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper"]]},"metadata":{"externalID":"c:@N@Overlay@S@HgiWrapper@F@CreatePlatformDefaultHgi#S","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreatePlatformDefaultHgi","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@N@Overlay@S@HgiWrapper","text":"HgiWrapper","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"CreatePlatformDefaultHgi"}],"role":"symbol","roleHeading":"Static Method","symbolKind":"method","title":"CreatePlatformDefaultHgi()","modules":[{"name":"OpenUSD"}]},"kind":"symbol","identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreatePlatformDefaultHgi","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreatePlatformDefaultHgi"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@N@Overlay@S@HgiWrapper","kind":"typeIdentifier","text":"HgiWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/hgiwrapper\/createplatformdefaulthgi"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/hgiwrapper\/createplatformdefaulthgi"]}],"sections":[],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"text":"Overlay","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","title":"Overlay","url":"\/documentation\/openusd\/overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/CreatePlatformDefaultHgi":{"url":"\/documentation\/openusd\/overlay\/hgiwrapper\/createplatformdefaulthgi","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreatePlatformDefaultHgi"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"HgiWrapper","preciseIdentifier":"c:@N@Overlay@S@HgiWrapper"}],"title":"CreatePlatformDefaultHgi()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CreatePlatformDefaultHgi"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/CreatePlatformDefaultHgi"},"doc://SwiftUsd/documentation/OpenUSD":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol","title":"OpenUSD","type":"topic","role":"collection","url":"\/documentation\/openusd"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HgiWrapper"}],"navigatorTitle":[{"kind":"identifier","text":"HgiWrapper"}],"url":"\/documentation\/openusd\/overlay\/hgiwrapper","kind":"symbol","role":"symbol","title":"class HgiWrapper"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Static Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"CreatePlatformDefaultHgi","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"CreatePlatformDefaultHgi","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"CreatePlatformDefaultHgi","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@Overlay@S@HgiWrapper","text":"HgiWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreatePlatformDefaultHgi"},{"kind":"text","text":"();"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","op":"replace"},{"value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","op":"replace"},{"value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","op":"add"},{"value":"CreatePlatformDefaultHgi","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreatePlatformDefaultHgi\/title","op":"replace"},{"value":[{"text":"CreatePlatformDefaultHgi","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreatePlatformDefaultHgi\/fragments","op":"replace"},{"value":[{"text":"CreatePlatformDefaultHgi","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1CreatePlatformDefaultHgi\/navigatorTitle","op":"replace"},{"value":"HgiWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/title","op":"replace"},{"value":[{"kind":"identifier","text":"HgiWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/fragments","op":"replace"},{"value":[{"text":"HgiWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}