{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/openusd\/overlay\/hgiwrapper\/vtvaluewrappinghgirawptr"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/hgiwrapper\/vtvaluewrappinghgirawptr"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"VtValueWrappingHgiRawPtr","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VtValueWrappingHgiRawPtr","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"VtValue","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@VtValue"}],"role":"symbol","symbolKind":"method","title":"VtValueWrappingHgiRawPtr()","externalID":"c:@N@Overlay@S@HgiWrapper@F@VtValueWrappingHgiRawPtr#1","roleHeading":"Instance Method","modules":[{"name":"OpenUSD"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"VtValueWrappingHgiRawPtr"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@VtValue","kind":"typeIdentifier","text":"VtValue"}],"platforms":["macOS"]}]}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/VtValueWrappingHgiRawPtr","interfaceLanguage":"swift"},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper/VtValueWrappingHgiRawPtr":{"kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/openusd\/overlay\/hgiwrapper\/vtvaluewrappinghgirawptr","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper\/VtValueWrappingHgiRawPtr","type":"topic","title":"VtValueWrappingHgiRawPtr()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"VtValueWrappingHgiRawPtr"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"VtValue","preciseIdentifier":"c:@N@pxr@S@VtValue"}],"navigatorTitle":[{"kind":"identifier","text":"VtValueWrappingHgiRawPtr"}]},"doc://SwiftUsd/documentation/OpenUSD":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol","title":"OpenUSD","type":"topic","role":"collection","url":"\/documentation\/openusd"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiWrapper":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiWrapper","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HgiWrapper"}],"navigatorTitle":[{"kind":"identifier","text":"HgiWrapper"}],"url":"\/documentation\/openusd\/overlay\/hgiwrapper","kind":"symbol","role":"symbol","title":"class HgiWrapper"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"text":"Overlay","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","title":"Overlay","url":"\/documentation\/openusd\/overlay"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"VtValueWrappingHgiRawPtr"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"VtValueWrappingHgiRawPtr"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"VtValueWrappingHgiRawPtr"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":"::","kind":"text"},{"text":"VtValue","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@VtValue"},{"text":" ","kind":"text"},{"text":"VtValueWrappingHgiRawPtr","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"const","kind":"keyword"},{"text":";","kind":"text"}],"platforms":["macOS"]}]}},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1VtValueWrappingHgiRawPtr\/title","value":"VtValueWrappingHgiRawPtr","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1VtValueWrappingHgiRawPtr\/fragments","value":[{"kind":"identifier","text":"VtValueWrappingHgiRawPtr"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper~1VtValueWrappingHgiRawPtr\/navigatorTitle","value":[{"kind":"identifier","text":"VtValueWrappingHgiRawPtr"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/title","value":"HgiWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/fragments","value":[{"kind":"identifier","text":"HgiWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiWrapper\/navigatorTitle","value":[{"text":"HgiWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"kind":"identifier","text":"Overlay"}],"op":"add"}],"traits":[{"interfaceLanguage":"occ"}]}]}