{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"OpenUSD"}],"title":"Type conversion"},"variants":[{"paths":["\/documentation\/swiftusd\/typeconversion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftusd\/typeconversion"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion"},"seeAlsoSections":[{"anchor":"New-symbol-documentation","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingLibWork","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions"],"title":"New symbol documentation","generated":true}],"kind":"article","hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"sections":[],"topicSections":[{"anchor":"Float-initializers","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift\/Float\/init(_:)"],"title":"Float initializers"},{"anchor":"String-initializers","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift\/String\/init(_:)-atr3","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift\/String\/init(_:)-6ndkh"],"title":"String initializers"}],"references":{"doc://SwiftUsd/documentation/OpenUSD/Swift/Float/init(_:)":{"url":"\/documentation\/openusd\/swift\/float\/init(_:)","role":"symbol","type":"topic","title":"init(_:)","abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"GfHalf","preciseIdentifier":"c:@N@pxr@GfHalf","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift\/Float\/init(_:)"},"doc://SwiftUsd/documentation/SwiftUsd/UsingLibWork":{"url":"\/documentation\/swiftusd\/usinglibwork","type":"topic","kind":"article","title":"Using libWork","abstract":[{"text":"Learn how to use the ","type":"text"},{"code":"pxr::Work","type":"codeVoice"},{"text":" library for multithreading in Swift","type":"text"}],"role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingLibWork"},"doc://SwiftUsd/documentation/OpenUSD":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol","title":"OpenUSD","type":"topic","role":"collection","url":"\/documentation\/openusd"},"doc://SwiftUsd/documentation/SwiftUsd/ConvenientExtensions":{"url":"\/documentation\/swiftusd\/convenientextensions","abstract":[{"text":"Extensions that make OpenUSD nicer to use in Swift","type":"text"}],"type":"topic","role":"collectionGroup","title":"Convenient extensions","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions"},"doc://SwiftUsd/documentation/SwiftUsd/UsingEditContexts":{"url":"\/documentation\/swiftusd\/usingeditcontexts","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","abstract":[{"type":"text","text":"Using "},{"type":"codeVoice","code":"pxr.UsdEditContext"},{"type":"text","text":" in Swift"}],"kind":"article","role":"collectionGroup","title":"Using edit contexts"},"doc://SwiftUsd/documentation/SwiftUsd/DereferencingPointers":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","kind":"article","url":"\/documentation\/swiftusd\/dereferencingpointers","abstract":[{"type":"text","text":"Safely dereferencing "},{"type":"codeVoice","code":"pxr.TfRefPtr"},{"type":"text","text":" and "},{"type":"codeVoice","code":"pxr.TfWeakPtr"},{"type":"text","text":" in Swift"}],"title":"Dereferencing pointers","role":"collectionGroup","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Swift/String/init(_:)-atr3":{"url":"\/documentation\/openusd\/swift\/string\/init(_:)-atr3","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift\/String\/init(_:)-atr3","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"TfToken","preciseIdentifier":"c:@N@pxr@S@TfToken"},{"kind":"text","text":")"}],"kind":"symbol","title":"init(_:)","type":"topic","role":"symbol"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfDiagnosticFacilities":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","title":"Working with Tf Diagnostic Facilities","role":"collectionGroup","abstract":[{"type":"text","text":"Learn how to use the Tf diagnostic facilities in Swift"}],"kind":"article","url":"\/documentation\/swiftusd\/workingwithtfdiagnosticfacilities"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfNotice":{"url":"\/documentation\/swiftusd\/workingwithtfnotice","abstract":[{"type":"text","text":"Learn how to use the TfNotice notification subsystem in Swift"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","kind":"article","title":"Working with TfNotice","role":"article"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfErrorMark":{"url":"\/documentation\/swiftusd\/workingwithtferrormark","title":"Working with TfErrorMark","kind":"article","type":"topic","abstract":[{"type":"text","text":"Learn how to use TfErrorMark in Swift"}],"role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark"},"doc://SwiftUsd/documentation/SwiftUsd/CreatingPointers":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","type":"topic","kind":"article","title":"Creating pointers","abstract":[{"type":"text","text":"Creating "},{"type":"codeVoice","code":"pxr.TfRefPtr"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"pxr.TfWeakPtr"},{"text":" in Swift","type":"text"}],"role":"collectionGroup","url":"\/documentation\/swiftusd\/creatingpointers"},"doc://SwiftUsd/documentation/SwiftUsd/CheckingForValidity":{"title":"Checking for validity","type":"topic","kind":"article","abstract":[{"text":"Checking for ","type":"text"},{"type":"codeVoice","code":"IsValid()"},{"text":" and null pointers in Swift","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","role":"article","url":"\/documentation\/swiftusd\/checkingforvalidity"},"doc://SwiftUsd/documentation/OpenUSD/Swift/String/init(_:)-6ndkh":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift\/String\/init(_:)-6ndkh","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"SdfPath","preciseIdentifier":"c:@N@pxr@S@SdfPath","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/openusd\/swift\/string\/init(_:)-6ndkh","kind":"symbol","title":"init(_:)","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":[{"generated":true,"anchor":"New-symbol-documentation","title":"New symbol documentation","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingLibWork","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions"]}],"op":"replace"}]}]}