{"abstract":[{"type":"text","text":"Learn how to use the TfNotice notification subsystem in Swift"}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"Overview","type":"heading"},{"inlineContent":[{"type":"text","text":"OpenUSD includes a notification subsystem based on "},{"type":"codeVoice","code":"pxr::TfNotice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"pxr::TfNotice::Register"},{"type":"text","text":" for use in C++. SwiftUsd exposes this system to Swift with minor modifications."}],"type":"paragraph"},{"inlineContent":[{"text":"Like in C++, TfNotice registration in Swift comes in three main forms:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-99j13","overridingTitleInlineContent":[{"type":"codeVoice","code":"pxr.TfNotice.Register(_:_:)"}],"overridingTitle":"pxr.TfNotice.Register(_:_:)","type":"reference"},{"text":" to register for a particular notice type, regardless of sender","type":"text"}]}]},{"content":[{"inlineContent":[{"overridingTitleInlineContent":[{"type":"codeVoice","code":"pxr.TfNotice.Register(_:_:_:)"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-8j5mu","isActive":true,"type":"reference","overridingTitle":"pxr.TfNotice.Register(_:_:_:)"},{"type":"text","text":" to register for a particular notice type from a specific sender, without retrieving the sender in the notification callback"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"overridingTitleInlineContent":[{"type":"codeVoice","code":"pxr.TfNotice.Register(_:_:_:)"}],"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-6we16","isActive":true,"overridingTitle":"pxr.TfNotice.Register(_:_:_:)"},{"type":"text","text":" to register for a particular notice type from a specific sender while retrieving the sender in the notification callback"}]}]}],"type":"unorderedList"},{"inlineContent":[{"type":"text","text":"Example usage:"}],"type":"paragraph"},{"code":["class StageWatcher {","    var stage: pxr.UsdStage","    var key: pxr.TfNotice.SwiftKey","","    init(stage: pxr.UsdStage) {","        self.stage = stage","","        key = pxr.TfNotice.Register(stage, pxr.UsdNotice.ObjectsChanged.self) { notice in","            print(\"Resynced: \\(notice.GetResyncedPaths())\")","            print(\"Changed info only: \\(notice.GetChangedInfoOnlyPaths())\")","        }","    }","    deinit {","        pxr.TfNotice.Revoke(key)","    }","}"],"type":"codeListing","syntax":"swift"},{"level":2,"text":"Downcasting and inheritance","anchor":"Downcasting-and-inheritance","type":"heading"},{"inlineContent":[{"type":"text","text":"When registering for a notice type, your notification callback may be called if notices that derive from the notice type you registered for are sent. To support conditional casting of "},{"type":"codeVoice","code":"TfNotice"},{"type":"text","text":" values in the notification callback, SwiftUsd provides "},{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/NoticeCaster"},{"type":"text","text":" and three auxillary forms of "},{"isActive":true,"overridingTitle":"pxr.TfNotice.Register()","overridingTitleInlineContent":[{"type":"codeVoice","code":"pxr.TfNotice.Register()"}],"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-99j13"},{"type":"text","text":" that provide the "},{"isActive":true,"overridingTitle":"NoticeCaster","overridingTitleInlineContent":[{"code":"NoticeCaster","type":"codeVoice"}],"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/NoticeCaster"},{"type":"text","text":" as a parameter to the notification callback:"}],"type":"paragraph"},{"code":["func registerWithDowncasting() {","    pxr.TfNotice.Register(pxr.UsdNotice.StageNotice.self) { notice, caster in","        if let layerMutingChanged = caster(pxr.UsdNotice.LayerMutingChanged.self) {","            print(\"Muted: \\(layerMutingChanged.GetMutedLayers())\")","            print(\"Unmuted: \\(layerMutingChanged.GetUnmutedLayers())\")","        } else if let stageEditTargetChanged = caster(pxr.UsdNotice.StageEditTargetChanged.self) {","            print(\"Stage edit target changed: \\(stageEditTargetChanged.GetStage())\")","        }","    }","}"],"type":"codeListing","syntax":"swift"},{"level":2,"text":"Cancellation","anchor":"Cancellation","type":"heading"},{"inlineContent":[{"text":"To cancel a notification callback, pass the return value from ","type":"text"},{"isActive":true,"type":"reference","overridingTitleInlineContent":[{"code":"pxr.TfNotice.Register","type":"codeVoice"}],"overridingTitle":"pxr.TfNotice.Register","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-99j13"},{"text":" to ","type":"text"},{"isActive":true,"type":"reference","overridingTitleInlineContent":[{"type":"codeVoice","code":"pxr.TfNotice.Revoke"}],"overridingTitle":"pxr.TfNotice.Revoke","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-31sr0"},{"text":":","type":"text"}],"type":"paragraph"},{"code":["func registerWithRevoking(stage: pxr.UsdStage) {","    let key = pxr.TfNotice.Register(stage, pxr.UsdNotice.StageContentsChanged.self) { _ in","        print(\"Stage contents changed\")","    }","","    stage.SetStartTimeCode(5) \/\/ prints \"Stage contents changed\"","    stage.SetEndTimeCode(7) \/\/ prints \"Stage contents changed\"","    pxr.TfNotice.Revoke(key)","    stage.SetTimeCodesPerSecond(60) \/\/ no print","}"],"type":"codeListing","syntax":"swift"},{"level":2,"text":"Swift-Cxx interoperability","anchor":"Swift-Cxx-interoperability","type":"heading"},{"inlineContent":[{"text":"The C++ and Swift versions of ","type":"text"},{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice","type":"reference","overridingTitle":"pxr::TfNotice","overridingTitleInlineContent":[{"type":"codeVoice","code":"pxr::TfNotice"}]},{"text":" can interoperate with each other. The C++ return type ","type":"text"},{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Key","type":"reference","overridingTitle":"pxr::TfNotice::Key","overridingTitleInlineContent":[{"type":"codeVoice","code":"pxr::TfNotice::Key"}]},{"text":" can be converted into the Swift return type ","type":"text"},{"isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey","type":"reference","overridingTitle":"pxr::TfNotice::SwiftKey","overridingTitleInlineContent":[{"type":"codeVoice","code":"pxr::TfNotice::SwiftKey"}]},{"text":", and both return types can be revoked from either language.","type":"text"}],"type":"paragraph"},{"code":["pxr::TfNotice::Key registerForChanges(pxr::UsdStageWeakPtr);"],"type":"codeListing","syntax":"c++"},{"code":["class KeyHolder {","    var keys = pxr.TfNotice.SwiftKeys()","","    init() {}","","    func callCppRegisterForChanges(stage: pxr.UsdStageWeakPtr) {","        let cppKey = registerForChanges(stage)","        let swiftKey = pxr.TfNotice.SwiftKey(cppKey)","        keys.push_back(swiftKey)","    }","","    func revokeAll() {","        pxr.TfNotice.Revoke(&keys)","    }","}"],"type":"codeListing","syntax":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"variants":[{"paths":["\/documentation\/swiftusd\/workingwithtfnotice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftusd\/workingwithtfnotice"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingLibWork","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion"],"title":"New symbol documentation","generated":true,"anchor":"New-symbol-documentation"}],"metadata":{"role":"article","roleHeading":"Article","title":"Working with TfNotice","modules":[{"name":"OpenUSD"}]},"references":{"doc://SwiftUsd/documentation/SwiftUsd/UsingEditContexts":{"url":"\/documentation\/swiftusd\/usingeditcontexts","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","abstract":[{"type":"text","text":"Using "},{"type":"codeVoice","code":"pxr.UsdEditContext"},{"type":"text","text":" in Swift"}],"kind":"article","role":"collectionGroup","title":"Using edit contexts"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice":{"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice","kind":"identifier"}],"role":"symbol","abstract":[],"title":"pxr.TfNotice","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice","kind":"symbol","navigatorTitle":[{"text":"TfNotice","kind":"identifier"}],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/NoticeCaster":{"abstract":[{"type":"text","text":"Utility struct that lets uses cast "},{"type":"codeVoice","code":"pxr::TfNotice"},{"type":"text","text":" subclasses in a "},{"type":"codeVoice","code":"pxr::TfNotice::Register"},{"type":"text","text":" callback"}],"url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/noticecaster","kind":"symbol","title":"pxr.TfNotice.NoticeCaster","type":"topic","role":"symbol","navigatorTitle":[{"text":"NoticeCaster","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NoticeCaster","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/NoticeCaster"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:_:)-8j5mu":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Register"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Notice"},{"kind":"text","text":", "},{"kind":"genericParameter","text":"Sender"},{"kind":"text","text":">("},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyxYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp","text":"Sender"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyxYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","text":"Notice"},{"kind":"text","text":".Type, ("},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyxYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","text":"Notice"},{"kind":"text","text":") -> ()) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","text":"SwiftKey"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-8j5mu","abstract":[{"type":"text","text":"Register a listener as being interested in a TfNotice from a particular sender."}],"kind":"symbol","role":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-8j5mu","type":"topic","title":"Register(_:_:_:)"},"doc://SwiftUsd/documentation/SwiftUsd/UsingLibWork":{"url":"\/documentation\/swiftusd\/usinglibwork","type":"topic","kind":"article","title":"Using libWork","abstract":[{"text":"Learn how to use the ","type":"text"},{"code":"pxr::Work","type":"codeVoice"},{"text":" library for multithreading in Swift","type":"text"}],"role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingLibWork"},"doc://SwiftUsd/documentation/SwiftUsd/TypeConversion":{"url":"\/documentation\/swiftusd\/typeconversion","title":"Type conversion","kind":"article","role":"collectionGroup","abstract":[],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion"},"doc://SwiftUsd/documentation/SwiftUsd/CreatingPointers":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","type":"topic","kind":"article","title":"Creating pointers","abstract":[{"type":"text","text":"Creating "},{"type":"codeVoice","code":"pxr.TfRefPtr"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"pxr.TfWeakPtr"},{"text":" in Swift","type":"text"}],"role":"collectionGroup","url":"\/documentation\/swiftusd\/creatingpointers"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfErrorMark":{"url":"\/documentation\/swiftusd\/workingwithtferrormark","title":"Working with TfErrorMark","kind":"article","type":"topic","abstract":[{"type":"text","text":"Learn how to use TfErrorMark in Swift"}],"role":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Key":{"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Key"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Key","title":"pxr.TfNotice.Key","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"identifier","preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice"},{"kind":"text","text":"."},{"kind":"identifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@Key","text":"Key"}],"url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/key","type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfDiagnosticFacilities":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","title":"Working with Tf Diagnostic Facilities","role":"collectionGroup","abstract":[{"type":"text","text":"Learn how to use the Tf diagnostic facilities in Swift"}],"kind":"article","url":"\/documentation\/swiftusd\/workingwithtfdiagnosticfacilities"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:)-99j13":{"kind":"symbol","role":"symbol","title":"Register(_:_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yxYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp"},{"text":".Type, (","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yxYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp"},{"text":") -> ()) -> ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}],"abstract":[{"text":"Register a listener as being interested in a TfNotice, regardless of sender.","type":"text"}],"url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:)-99j13","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-99j13"},"doc://SwiftUsd/documentation/SwiftUsd/ConvenientExtensions":{"url":"\/documentation\/swiftusd\/convenientextensions","abstract":[{"text":"Extensions that make OpenUSD nicer to use in Swift","type":"text"}],"type":"topic","role":"collectionGroup","title":"Convenient extensions","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions"},"doc://SwiftUsd/documentation/SwiftUsd/DereferencingPointers":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","kind":"article","url":"\/documentation\/swiftusd\/dereferencingpointers","abstract":[{"type":"text","text":"Safely dereferencing "},{"type":"codeVoice","code":"pxr.TfRefPtr"},{"type":"text","text":" and "},{"type":"codeVoice","code":"pxr.TfWeakPtr"},{"type":"text","text":" in Swift"}],"title":"Dereferencing pointers","role":"collectionGroup","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol","title":"OpenUSD","type":"topic","role":"collection","url":"\/documentation\/openusd"},"doc://SwiftUsd/documentation/OpenUSD/Revoke-31sr0":{"url":"\/documentation\/openusd\/revoke-31sr0","role":"symbol","title":"Revoke(_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Revoke","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","text":"SwiftKey","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:b","text":"Bool","kind":"typeIdentifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-31sr0","navigatorTitle":[{"text":"Revoke","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:_:)-6we16":{"role":"symbol","title":"Register(_:_:_:)","type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-6we16","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"Sender","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Sender","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"text":", ","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"text":".Type, (","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"text":", ","kind":"text"},{"text":"Sender","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"text":") -> ()) -> ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-6we16","kind":"symbol","abstract":[{"type":"text","text":"Register a listener as being interested in a TfNotice from a particular sender."}]},"doc://SwiftUsd/documentation/OpenUSD/SwiftKey":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SwiftKey","kind":"identifier"}],"navigatorTitle":[{"text":"SwiftKey","kind":"identifier"}],"title":"class SwiftKey","url":"\/documentation\/openusd\/swiftkey","abstract":[{"text":"A key representing a listener registered from either Swift or C++","type":"text"}],"role":"symbol"},"doc://SwiftUsd/documentation/SwiftUsd/CheckingForValidity":{"title":"Checking for validity","type":"topic","kind":"article","abstract":[{"text":"Checking for ","type":"text"},{"type":"codeVoice","code":"IsValid()"},{"text":" and null pointers in Swift","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","role":"article","url":"\/documentation\/swiftusd\/checkingforvalidity"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"title":"New symbol documentation","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingLibWork","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion"],"generated":true,"anchor":"New-symbol-documentation"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-31sr0\/title","value":"Revoke","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-31sr0\/fragments","value":[{"text":"Revoke","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-31sr0\/navigatorTitle","value":[{"text":"Revoke","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/title","value":"SwiftKey","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/fragments","value":[{"text":"SwiftKey","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/navigatorTitle","value":[{"text":"SwiftKey","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}