{"topicSections":[{"abstract":[{"text":"In Swift, these functions live under ","type":"text"},{"code":"Overlay","type":"codeVoice"},{"text":".","type":"text"}],"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/CopyTextureGpuToCpu","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/CreateExtentAttr","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetDescriptor","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetStage","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetAttr","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiTextureHandleGetTextureId","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/allowedTokensForAttribute","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetPath-1gxko","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/DefaultPropertyPredicateFunc","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetMetadata","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SetMetadata","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HasMetadata","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ClearMetadata","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HasAuthoredMetadata","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetPath-9ig6g","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SdfLayer\/TraversalFunction","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdProperty_As","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Get","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Set"],"anchor":"Topics"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedFunctions","interfaceLanguage":"swift"},"kind":"article","metadata":{"title":"Wrapped functions","modules":[{"name":"OpenUSD"}],"role":"collectionGroup","roleHeading":"API Collection"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"seeAlsoSections":[{"title":"Wrapped symbol documentation","generated":true,"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedTypes","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedEnums","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedOperators"],"anchor":"Wrapped-symbol-documentation"}],"variants":[{"paths":["\/documentation\/swiftusd\/wrappedfunctions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftusd\/wrappedfunctions"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/HasMetadata":{"navigatorTitle":[{"kind":"identifier","text":"HasMetadata"}],"abstract":[],"url":"\/documentation\/openusd\/overlay\/hasmetadata","title":"HasMetadata(_:_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HasMetadata","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"HasMetadata"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@UsdRelationship","kind":"typeIdentifier","text":"UsdRelationship"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@TfToken","kind":"typeIdentifier","text":"TfToken"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:b","kind":"typeIdentifier","text":"Bool"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/SdfLayer/TraversalFunction":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SdfLayer\/TraversalFunction","navigatorTitle":[{"text":"TraversalFunction","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TraversalFunction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^","kind":"text"}],"url":"\/documentation\/openusd\/overlay\/sdflayer\/traversalfunction","kind":"symbol","abstract":[],"role":"symbol","type":"topic","title":"TraversalFunction(_:)"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"text":"Overlay","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","title":"Overlay","url":"\/documentation\/openusd\/overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/CopyTextureGpuToCpu":{"navigatorTitle":[{"kind":"identifier","text":"CopyTextureGpuToCpu"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/CopyTextureGpuToCpu","type":"topic","kind":"symbol","title":"CopyTextureGpuToCpu(_:_:)","abstract":[],"url":"\/documentation\/openusd\/overlay\/copytexturegputocpu","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CopyTextureGpuToCpu"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@std","text":"std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@shared_ptr","text":"std::shared_ptr"},{"kind":"text","text":"<"},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiBlitCmds","text":"HgiBlitCmds"},{"kind":"text","text":">"},{"kind":"text","text":", "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiTextureGpuToCpuOp","text":"HgiTextureGpuToCpuOp"},{"kind":"text","text":")"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/GetDescriptor":{"navigatorTitle":[{"kind":"identifier","text":"GetDescriptor"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetDescriptor","type":"topic","kind":"symbol","title":"GetDescriptor(_:)","abstract":[],"url":"\/documentation\/openusd\/overlay\/getdescriptor","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetDescriptor"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiTexture","text":"HgiTextureHandle"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiTextureDesc","text":"HgiTextureDesc"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Set":{"title":"Set(_:_:_:)","kind":"symbol","url":"\/documentation\/openusd\/overlay\/set","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Set"},{"kind":"text","text":"("},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"UsdAttribute","preciseIdentifier":"c:@N@pxr@S@UsdAttribute"},{"kind":"text","text":", "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"VtValue","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@VtValue"},{"text":", ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"UsdTimeCode","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdTimeCode"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"Set","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Set"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ClearMetadata":{"navigatorTitle":[{"kind":"identifier","text":"ClearMetadata"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ClearMetadata","title":"ClearMetadata(_:_:)","type":"topic","url":"\/documentation\/openusd\/overlay\/clearmetadata","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClearMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"UsdRelationship","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdRelationship"},{"text":", ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"TfToken","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfToken"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/Get":{"url":"\/documentation\/openusd\/overlay\/get","title":"Get(_:_:_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Get"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@UsdAttribute","kind":"typeIdentifier","text":"UsdAttribute"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@VtValue","kind":"typeIdentifier","text":"VtValue"},{"kind":"text","text":">"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@UsdTimeCode","kind":"typeIdentifier","text":"UsdTimeCode"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:b","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"Get"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/Get","type":"topic","abstract":[],"role":"symbol"},"doc://SwiftUsd/documentation/SwiftUsd/WrappedEnums":{"type":"topic","url":"\/documentation\/swiftusd\/wrappedenums","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedEnums","abstract":[],"title":"Wrapped enums","role":"article","kind":"article"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiTextureHandleGetTextureId":{"navigatorTitle":[{"text":"HgiTextureHandleGetTextureId","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiTextureHandleGetTextureId","title":"HgiTextureHandleGetTextureId(_:)","type":"topic","url":"\/documentation\/openusd\/overlay\/hgitexturehandlegettextureid","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiTextureHandleGetTextureId","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"HgiTextureHandle","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HgiHandle>#$@N@pxr@S@HgiTexture"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"id<MTLTexture>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MTLTexture"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/GetPath-1gxko":{"navigatorTitle":[{"kind":"identifier","text":"GetPath"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetPath-1gxko","type":"topic","kind":"symbol","title":"GetPath(_:)","abstract":[],"url":"\/documentation\/openusd\/overlay\/getpath-1gxko","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetPath"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdAttribute","text":"UsdAttribute"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@SdfPath","text":"SdfPath"}]},"doc://SwiftUsd/documentation/SwiftUsd/WrappedOperators":{"title":"Wrapped operators","abstract":[],"role":"collectionGroup","url":"\/documentation\/swiftusd\/wrappedoperators","kind":"article","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedOperators"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdProperty_As":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdProperty_As","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"UsdProperty","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdProperty"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"UsdRelationship","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdRelationship"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdProperty_As","kind":"symbol","navigatorTitle":[{"text":"UsdProperty_As","kind":"identifier"}],"url":"\/documentation\/openusd\/overlay\/usdproperty_as","type":"topic","title":"UsdProperty_As(_:)","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/GetAttr":{"navigatorTitle":[{"kind":"identifier","text":"GetAttr"}],"title":"GetAttr(_:)","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetAttr","url":"\/documentation\/openusd\/overlay\/getattr","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetAttr","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdGeomXformOp","preciseIdentifier":"c:@N@pxr@S@UsdGeomXformOp","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdAttribute","preciseIdentifier":"c:@N@pxr@S@UsdAttribute","kind":"typeIdentifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/GetStage":{"navigatorTitle":[{"text":"GetStage","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetStage","type":"topic","kind":"symbol","title":"GetStage(_:)","abstract":[],"url":"\/documentation\/openusd\/overlay\/getstage","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetStage"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdAttribute","text":"UsdAttribute"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@T@UsdStagePtr","text":"UsdStagePtr"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/GetMetadata":{"navigatorTitle":[{"kind":"identifier","text":"GetMetadata"}],"abstract":[],"url":"\/documentation\/openusd\/overlay\/getmetadata","title":"GetMetadata(_:_:_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetMetadata","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetMetadata"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@UsdRelationship","kind":"typeIdentifier","text":"UsdRelationship"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@TfToken","kind":"typeIdentifier","text":"TfToken"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@VtValue","kind":"typeIdentifier","text":"VtValue"},{"kind":"text","text":">"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:b","kind":"typeIdentifier","text":"Bool"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HasAuthoredMetadata":{"navigatorTitle":[{"text":"HasAuthoredMetadata","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HasAuthoredMetadata","type":"topic","kind":"symbol","title":"HasAuthoredMetadata(_:_:)","abstract":[],"url":"\/documentation\/openusd\/overlay\/hasauthoredmetadata","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"HasAuthoredMetadata"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdRelationship","text":"UsdRelationship"},{"kind":"text","text":", "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfToken","text":"TfToken"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:b","text":"Bool"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/GetPath-9ig6g":{"navigatorTitle":[{"text":"GetPath","kind":"identifier"}],"title":"GetPath(_:)","url":"\/documentation\/openusd\/overlay\/getpath-9ig6g","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"UsdRelationship","preciseIdentifier":"c:@N@pxr@S@UsdRelationship","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"SdfPath","preciseIdentifier":"c:@N@pxr@S@SdfPath","kind":"typeIdentifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/GetPath-9ig6g","type":"topic","kind":"symbol","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/allowedTokensForAttribute":{"navigatorTitle":[{"kind":"identifier","text":"allowedTokensForAttribute"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/allowedTokensForAttribute","abstract":[],"kind":"symbol","title":"allowedTokensForAttribute(_:_:)","url":"\/documentation\/openusd\/overlay\/allowedtokensforattribute","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowedTokensForAttribute"},{"kind":"text","text":"("},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"UsdAttribute","preciseIdentifier":"c:@N@pxr@S@UsdAttribute"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"pxr::VtArray","preciseIdentifier":"c:@N@pxr@ST>1#T@VtArray"},{"kind":"text","text":"<"},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"TfToken","preciseIdentifier":"c:@N@pxr@S@TfToken"},{"kind":"text","text":"> "},{"kind":"text","text":">"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"c:b"}]},"doc://SwiftUsd/documentation/SwiftUsd/WrappedTypes":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedTypes","kind":"article","role":"collectionGroup","title":"Wrapped types","abstract":[],"type":"topic","url":"\/documentation\/swiftusd\/wrappedtypes"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/DefaultPropertyPredicateFunc":{"navigatorTitle":[{"kind":"identifier","text":"DefaultPropertyPredicateFunc"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/DefaultPropertyPredicateFunc","abstract":[],"kind":"symbol","title":"DefaultPropertyPredicateFunc","url":"\/documentation\/openusd\/overlay\/defaultpropertypredicatefunc","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultPropertyPredicateFunc"},{"kind":"text","text":": "},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"std::function","preciseIdentifier":"c:@N@std@N@__1@ST>1#T@function"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"_Bool (const class pxr::TfToken &)","preciseIdentifier":"c:Fb(#&1$@N@pxr@S@TfToken)"},{"kind":"text","text":">"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/CreateExtentAttr":{"navigatorTitle":[{"kind":"identifier","text":"CreateExtentAttr"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/CreateExtentAttr","type":"topic","kind":"symbol","title":"CreateExtentAttr(_:_:_:)","abstract":[],"url":"\/documentation\/openusd\/overlay\/createextentattr","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateExtentAttr"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdGeomMesh","text":"UsdGeomMesh"},{"kind":"text","text":", "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@VtValue","text":"VtValue"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:b","text":"Bool"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@UsdAttribute","text":"UsdAttribute"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/SetMetadata":{"navigatorTitle":[{"kind":"identifier","text":"SetMetadata"}],"abstract":[],"url":"\/documentation\/openusd\/overlay\/setmetadata","title":"SetMetadata(_:_:_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/SetMetadata","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SetMetadata"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@UsdRelationship","kind":"typeIdentifier","text":"UsdRelationship"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@TfToken","kind":"typeIdentifier","text":"TfToken"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@VtValue","kind":"typeIdentifier","text":"VtValue"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:b","kind":"typeIdentifier","text":"Bool"}]},"doc://SwiftUsd/documentation/OpenUSD":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol","title":"OpenUSD","type":"topic","role":"collection","url":"\/documentation\/openusd"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Wrapped-symbol-documentation","generated":true,"title":"Wrapped symbol documentation","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedTypes","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedEnums","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WrappedOperators"]}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}]},{"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"kind":"identifier","text":"Overlay"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}