{"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitcommandbufferwaittype\/commitcommandbuffer_nowait"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitcommandbufferwaittype\/commitcommandbuffer_nowait"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"case","externalID":"c:@N@Overlay@S@HgiMetalWrapper@E@CommitCommandBufferWaitType@CommitCommandBuffer_NoWait","roleHeading":"Enumeration Case","role":"symbol","title":"CommitCommandBuffer_NoWait","navigatorTitle":[{"kind":"identifier","text":"CommitCommandBuffer_NoWait"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommitCommandBuffer_NoWait"}],"modules":[{"name":"OpenUSD"}]},"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType\/CommitCommandBuffer_NoWait","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommitCommandBuffer_NoWait","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}]}],"sections":[],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper/CommitCommandBufferWaitType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommitCommandBufferWaitType"}],"role":"symbol","title":"CommitCommandBufferWaitType","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitcommandbufferwaittype","abstract":[],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType","navigatorTitle":[{"kind":"identifier","text":"CommitCommandBufferWaitType"}],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper":{"navigatorTitle":[{"text":"HgiMetalWrapper","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper","type":"topic","title":"class HgiMetalWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HgiMetalWrapper","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HgiMetalWrapper/CommitCommandBufferWaitType/CommitCommandBuffer_NoWait":{"abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/hgimetalwrapper\/commitcommandbufferwaittype\/commitcommandbuffer_nowait","type":"topic","title":"CommitCommandBuffer_NoWait","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HgiMetalWrapper\/CommitCommandBufferWaitType\/CommitCommandBuffer_NoWait","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommitCommandBuffer_NoWait","kind":"identifier"}],"navigatorTitle":[{"text":"CommitCommandBuffer_NoWait","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"text":"Overlay","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","title":"Overlay","url":"\/documentation\/openusd\/overlay"},"doc://SwiftUsd/documentation/OpenUSD":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol","title":"OpenUSD","type":"topic","role":"collection","url":"\/documentation\/openusd"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"CommitCommandBuffer_NoWait"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"CommitCommandBuffer_NoWait"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CommitCommandBuffer_NoWait"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"CommitCommandBuffer_NoWait"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType\/title","value":"CommitCommandBufferWaitType"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType\/fragments","value":[{"text":"CommitCommandBufferWaitType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType\/navigatorTitle","value":[{"text":"CommitCommandBufferWaitType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/title","value":"HgiMetalWrapper"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/fragments","value":[{"kind":"identifier","text":"HgiMetalWrapper"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"HgiMetalWrapper"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType~1CommitCommandBuffer_NoWait\/title","value":"CommitCommandBuffer_NoWait"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType~1CommitCommandBuffer_NoWait\/fragments","value":[{"text":"CommitCommandBuffer_NoWait","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HgiMetalWrapper~1CommitCommandBufferWaitType~1CommitCommandBuffer_NoWait\/navigatorTitle","value":[{"text":"CommitCommandBuffer_NoWait","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}]},{"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"kind":"identifier","text":"Overlay"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}