{"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/NoticeCaster\/callAsFunction(_:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/NoticeCaster"]]},"abstract":[{"type":"text","text":"Casting operator."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"callAsFunction","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV14callAsFunctionyxSgxmSo8SwiftUsdOAEE0eF8ProtocolRzlF1TL_xmfp","text":"T"},{"kind":"text","text":".Type = T.self) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV14callAsFunctionyxSgxmSo8SwiftUsdOAEE0eF8ProtocolRzlF1TL_xmfp","text":"T"},{"kind":"text","text":"? "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@SwiftUsd","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd","text":"SwiftUsd"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:So8SwiftUsdO7OpenUSDE16TfNoticeProtocolP","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/SwiftUsd\/TfNoticeProtocol","text":"TfNoticeProtocol"}]}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns the casted "},{"code":"pxr::TfNotice","type":"codeVoice"},{"type":"text","text":" during a "},{"code":"pxr::TfNotice::Register","type":"codeVoice"},{"type":"text","text":" callback, or null if casting failed."},{"type":"text","text":" "},{"type":"text","text":"Equivalent to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/NoticeCaster\/cast(to:)"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/c++\/pxr\/tfnotice\/noticecaster\/callasfunction(_:)"]}],"metadata":{"title":"callAsFunction(_:)","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"callAsFunction","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV14callAsFunctionyxSgxmSo8SwiftUsdOAEE0eF8ProtocolRzlF1TL_xmfp","text":"T","kind":"typeIdentifier"},{"text":".Type) -> ","kind":"text"},{"preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV14callAsFunctionyxSgxmSo8SwiftUsdOAEE0eF8ProtocolRzlF1TL_xmfp","text":"T","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV14callAsFunctionyxSgxmSo8SwiftUsdOAEE0eF8ProtocolRzlF","modules":[{"name":"OpenUSD"}]},"references":{"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/NoticeCaster/callAsFunction(_:)":{"type":"topic","title":"callAsFunction(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"callAsFunction","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV14callAsFunctionyxSgxmSo8SwiftUsdOAEE0eF8ProtocolRzlF1TL_xmfp"},{"text":".Type) -> ","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV14callAsFunctionyxSgxmSo8SwiftUsdOAEE0eF8ProtocolRzlF1TL_xmfp"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/NoticeCaster\/callAsFunction(_:)","abstract":[{"text":"Casting operator.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/noticecaster\/callasfunction(_:)"},"doc://SwiftUsd/documentation/OpenUSD/C++/SwiftUsd/TfNoticeProtocol":{"url":"\/documentation\/openusd\/c++\/swiftusd\/tfnoticeprotocol","abstract":[{"type":"text","text":"Protocol representing "},{"type":"codeVoice","code":"pxr::TfNotice"},{"type":"text","text":" subclasses."}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/SwiftUsd\/TfNoticeProtocol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TfNoticeProtocol"}],"title":"SwiftUsd.TfNoticeProtocol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TfNoticeProtocol"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/NoticeCaster/cast(to:)":{"url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/noticecaster\/cast(to:)","type":"topic","abstract":[{"text":"Casting operator.","type":"text"}],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/NoticeCaster\/cast(to:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cast","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV4cast2toxSgxm_tSo8SwiftUsdOAEE0eF8ProtocolRzlF1TL_xmfp"},{"text":".Type) -> ","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV4cast2toxSgxm_tSo8SwiftUsdOAEE0eF8ProtocolRzlF1TL_xmfp"},{"text":"?","kind":"text"}],"title":"cast(to:)","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/NoticeCaster":{"abstract":[{"type":"text","text":"Utility struct that lets uses cast "},{"type":"codeVoice","code":"pxr::TfNotice"},{"type":"text","text":" subclasses in a "},{"type":"codeVoice","code":"pxr::TfNotice::Register"},{"type":"text","text":" callback"}],"url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/noticecaster","kind":"symbol","title":"pxr.TfNotice.NoticeCaster","type":"topic","role":"symbol","navigatorTitle":[{"text":"NoticeCaster","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NoticeCaster","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/NoticeCaster"},"doc://SwiftUsd/documentation/OpenUSD/C++":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++","kind":"symbol","title":"C++","abstract":[],"role":"collection","url":"\/documentation\/openusd\/c++"},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd":{"url":"\/documentation\/openusd\/swiftusd","role":"symbol","title":"SwiftUsd","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd","fragments":[{"kind":"identifier","text":"SwiftUsd"}]},"doc://SwiftUsd/documentation/OpenUSD":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol","title":"OpenUSD","type":"topic","role":"collection","url":"\/documentation\/openusd"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice":{"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice","kind":"identifier"}],"role":"symbol","abstract":[],"title":"pxr.TfNotice","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice","kind":"symbol","navigatorTitle":[{"text":"TfNotice","kind":"identifier"}],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr":{"navigatorTitle":[{"text":"pxr","kind":"identifier"}],"url":"\/documentation\/openusd\/c++\/pxr","title":"pxr","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr","abstract":[],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/title","value":"SwiftUsd","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/fragments","value":[{"kind":"identifier","text":"SwiftUsd"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/navigatorTitle","value":[{"text":"SwiftUsd","kind":"identifier"}],"op":"add"}],"traits":[{"interfaceLanguage":"occ"}]}]}