{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/SwiftKey-5p2qq"},"metadata":{"externalID":"c:@N@pxr@S@TfNotice@S@SwiftKey@F@SwiftKey#","navigatorTitle":[{"text":"SwiftKey","kind":"identifier"}],"role":"symbol","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier"}],"modules":[{"name":"OpenUSD"}],"roleHeading":"Initializer","title":"init()"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Creates an empty (invalid) key not tied to any listener."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/swiftkey\/swiftkey-5p2qq"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/swiftkey\/swiftkey-5p2qq"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SwiftKey"}],"platforms":["macOS"]}],"kind":"declarations"}],"references":{"doc://SwiftUsd/documentation/OpenUSD/SwiftKey/SwiftKey-5p2qq":{"url":"\/documentation\/openusd\/swiftkey\/swiftkey-5p2qq","kind":"symbol","role":"symbol","abstract":[{"text":"Creates an empty (invalid) key not tied to any listener.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SwiftKey","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/SwiftKey-5p2qq","title":"init()"},"doc://SwiftUsd/documentation/OpenUSD":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol","title":"OpenUSD","type":"topic","role":"collection","url":"\/documentation\/openusd"},"doc://SwiftUsd/documentation/OpenUSD/SwiftKey":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SwiftKey","kind":"identifier"}],"navigatorTitle":[{"text":"SwiftKey","kind":"identifier"}],"title":"class SwiftKey","url":"\/documentation\/openusd\/swiftkey","abstract":[{"text":"A key representing a listener registered from either Swift or C++","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Constructor","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SwiftKey","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SwiftKey"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SwiftKey","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"SwiftKey","kind":"identifier"},{"text":"();","kind":"text"}],"languages":["occ"],"platforms":["macOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SwiftKey","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1SwiftKey-5p2qq\/title","op":"replace"},{"value":[{"text":"SwiftKey","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1SwiftKey-5p2qq\/fragments","op":"replace"},{"value":[{"text":"SwiftKey","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1SwiftKey-5p2qq\/navigatorTitle","op":"replace"},{"value":"SwiftKey","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SwiftKey"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SwiftKey"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}