{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/UsdImagingGLEngineWrapper-9gwfs"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rootPath"},{"kind":"text","text":": "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@SdfPath","text":"SdfPath"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"excludedPaths"},{"kind":"text","text":": "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"SdfPathVector","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@SdfPath#$@N@std@N@__1@S@allocator>#S0_"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"invisedPaths"},{"kind":"text","text":": "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"SdfPathVector","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@SdfPath#$@N@std@N@__1@S@allocator>#S0_"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sceneDelegateID"},{"kind":"text","text":": "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"SdfPath","preciseIdentifier":"c:@N@pxr@S@SdfPath"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"driver"},{"kind":"text","text":": "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"HdDriver","preciseIdentifier":"c:@N@pxr@S@HdDriver"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rendererPluginId"},{"kind":"text","text":": "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"TfToken","preciseIdentifier":"c:@N@pxr@S@TfToken"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gpuEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"_Bool","preciseIdentifier":"c:b"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"displayUnloadedPrimsWithBounds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"_Bool","preciseIdentifier":"c:b"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"allowAsynchronousSceneProcessing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"_Bool","preciseIdentifier":"c:b"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"enableUsdDrawModes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"_Bool","preciseIdentifier":"c:b"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"UsdImagingGLEngineWrapper"}],"platforms":["macOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/usdimagingglenginewrapper-9gwfs"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/usdimagingglenginewrapper-9gwfs"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"init","modules":[{"name":"OpenUSD"}],"title":"init(_:_:_:_:_:_:_:_:_:_:)","externalID":"c:@N@Overlay@S@UsdImagingGLEngineWrapper@F@UsdImagingGLEngineWrapper#&1$@N@pxr@S@SdfPath#&1$@N@std@N@__1@S@vector>#S1_#$@N@std@N@__1@S@allocator>#S1_#S2_#S0_#&1$@N@pxr@S@HdDriver#&1$@N@pxr@S@TfToken#b#b#b#b#","roleHeading":"Initializer","navigatorTitle":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"SdfPath","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@SdfPath"},{"text":", ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"SdfPathVector","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@SdfPath#$@N@std@N@__1@S@allocator>#S0_"},{"text":", ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"SdfPathVector","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@SdfPath#$@N@std@N@__1@S@allocator>#S0_"},{"text":", ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"SdfPath","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@SdfPath"},{"text":", ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"HdDriver","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HdDriver"},{"text":", ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"TfToken","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfToken"},{"text":", ","kind":"text"},{"text":"_Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"},{"text":", ","kind":"text"},{"text":"_Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"},{"text":", ","kind":"text"},{"text":"_Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"},{"text":", ","kind":"text"},{"text":"_Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"UsdImagingGLEngineWrapper","kind":"typeIdentifier"}]},"references":{"doc://SwiftUsd/documentation/OpenUSD":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol","title":"OpenUSD","type":"topic","role":"collection","url":"\/documentation\/openusd"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"text":"Overlay","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","title":"Overlay","url":"\/documentation\/openusd\/overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/UsdImagingGLEngineWrapper-9gwfs":{"navigatorTitle":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/UsdImagingGLEngineWrapper-9gwfs","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/usdimagingglenginewrapper-9gwfs","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"SdfPath","preciseIdentifier":"c:@N@pxr@S@SdfPath"},{"kind":"text","text":", "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"SdfPathVector","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@SdfPath#$@N@std@N@__1@S@allocator>#S0_"},{"kind":"text","text":", "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"SdfPathVector","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@SdfPath#$@N@std@N@__1@S@allocator>#S0_"},{"kind":"text","text":", "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"SdfPath","preciseIdentifier":"c:@N@pxr@S@SdfPath"},{"kind":"text","text":", "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"HdDriver","preciseIdentifier":"c:@N@pxr@S@HdDriver"},{"kind":"text","text":", "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"TfToken","preciseIdentifier":"c:@N@pxr@S@TfToken"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"_Bool","preciseIdentifier":"c:b"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"_Bool","preciseIdentifier":"c:b"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"_Bool","preciseIdentifier":"c:b"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"_Bool","preciseIdentifier":"c:b"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"UsdImagingGLEngineWrapper"}],"title":"init(_:_:_:_:_:_:_:_:_:_:)","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper":{"url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","title":"class UsdImagingGLEngineWrapper","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Constructor"},{"op":"replace","path":"\/metadata\/title","value":"UsdImagingGLEngineWrapper"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"},{"text":"(","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":"::","kind":"text"},{"text":"SdfPath","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@SdfPath"},{"text":" & ","kind":"text"},{"text":"rootPath","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":"::","kind":"text"},{"text":"SdfPathVector","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@SdfPath#$@N@std@N@__1@S@allocator>#S0_"},{"text":" & ","kind":"text"},{"text":"excludedPaths","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":"::","kind":"text"},{"text":"SdfPathVector","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@SdfPath#$@N@std@N@__1@S@allocator>#S0_"},{"text":" & ","kind":"text"},{"text":"invisedPaths","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":"::","kind":"text"},{"text":"SdfPath","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@SdfPath"},{"text":" & ","kind":"text"},{"text":"sceneDelegateID","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":"::","kind":"text"},{"text":"HdDriver","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@HdDriver"},{"text":" & ","kind":"text"},{"text":"driver","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":"::","kind":"text"},{"text":"TfToken","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfToken"},{"text":" & ","kind":"text"},{"text":"rendererPluginId","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"},{"text":" ","kind":"text"},{"text":"gpuEnabled","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"},{"text":" ","kind":"text"},{"text":"displayUnloadedPrimsWithBounds","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"},{"text":" ","kind":"text"},{"text":"allowAsynchronousSceneProcessing","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"},{"text":" ","kind":"text"},{"text":"enableUsdDrawModes","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"kind":"identifier","text":"Overlay"}],"op":"add"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1UsdImagingGLEngineWrapper-9gwfs\/title","value":"UsdImagingGLEngineWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1UsdImagingGLEngineWrapper-9gwfs\/fragments","value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1UsdImagingGLEngineWrapper-9gwfs\/navigatorTitle","value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/title","value":"UsdImagingGLEngineWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/fragments","value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}