{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Register"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Notice"},{"kind":"text","text":", "},{"kind":"genericParameter","text":"Sender"},{"kind":"text","text":">("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Sender","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Notice","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"kind":"text","text":".Type = Notice.self, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"Notice","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Sender","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"kind":"text","text":") -> ()) -> "},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"kind":"text","text":"."},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey","kind":"typeIdentifier","text":"SwiftKey","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"},{"kind":"text","text":" "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Notice"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd","kind":"typeIdentifier","text":"SwiftUsd","preciseIdentifier":"c:@N@SwiftUsd"},{"kind":"text","text":"."},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/SwiftUsd\/TfNoticeProtocol","kind":"typeIdentifier","text":"TfNoticeProtocol","preciseIdentifier":"s:So8SwiftUsdO7OpenUSDE16TfNoticeProtocolP"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Sender"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","kind":"typeIdentifier","text":"Overlay","preciseIdentifier":"c:@N@Overlay"},{"kind":"text","text":"."},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_TfWeakBaseProtocol","kind":"typeIdentifier","text":"_TfWeakBaseProtocol","preciseIdentifier":"s:So7OverlayO7OpenUSDE19_TfWeakBaseProtocolP"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Sender"},{"kind":"text","text":" == "},{"kind":"typeIdentifier","text":"Sender"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"_SelfType","preciseIdentifier":"s:So7OverlayO7OpenUSDE30_SwiftUsdReferenceTypeProtocolP05_SelfG0Qa"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Registration of interest in a notice class "},{"code":"N","type":"codeVoice"},{"type":"text","text":" automatically registers interest in all classes derived from "},{"code":"N","type":"codeVoice"},{"type":"text","text":". When a notice of appropriate type is received, the "},{"code":"callback","type":"codeVoice"},{"type":"text","text":" is called with the notice."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"To reverse the registration, call "},{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-31sr0"},{"type":"text","text":" on the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey"},{"type":"text","text":" object returned by this call."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This form of registration listens for notices from a particular sender, receiving the sender in the callback. The sender being registered for must be derived from "},{"code":"pxr::TfWeakBase","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"text":"Additionally, all forms of registration can also support dynamically downcasting notice types in the callback (see overloads).","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice"]]},"kind":"symbol","seeAlsoSections":[{"generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-99j13","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-8j5mu","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-2cm0u","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-7toj3","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-17h9z","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-31sr0","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-2xoh5","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-7ycue","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-9e095"],"title":"Type Methods"}],"metadata":{"title":"Register(_:_:_:)","roleHeading":"Type Method","externalID":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ","symbolKind":"method","role":"symbol","extendedModule":"C++","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"Sender","kind":"genericParameter"},{"text":">(","kind":"text"},{"preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp","text":"Sender","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","text":"Notice","kind":"typeIdentifier"},{"text":".Type, (","kind":"text"},{"preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","text":"Notice","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp","text":"Sender","kind":"typeIdentifier"},{"text":") -> ()) -> ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","text":"SwiftKey","kind":"typeIdentifier"}],"modules":[{"relatedModules":["C++"],"name":"OpenUSD"}]},"sections":[],"variants":[{"paths":["\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-6we16"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Register a listener as being interested in a TfNotice from a particular sender.","type":"text"}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-6we16","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://SwiftUsd/documentation/OpenUSD/RevokeAndWait-7ycue":{"abstract":[],"kind":"symbol","type":"topic","title":"RevokeAndWait(_:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RevokeAndWait","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"}],"navigatorTitle":[{"text":"RevokeAndWait","kind":"identifier"}],"url":"\/documentation\/openusd\/revokeandwait-7ycue","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-7ycue"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:)-99j13":{"kind":"symbol","role":"symbol","title":"Register(_:_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yxYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp"},{"text":".Type, (","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yxYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp"},{"text":") -> ()) -> ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}],"abstract":[{"text":"Register a listener as being interested in a TfNotice, regardless of sender.","type":"text"}],"url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:)-99j13","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-99j13"},"doc://SwiftUsd/documentation/OpenUSD/C++/Overlay/_TfWeakBaseProtocol":{"title":"Overlay._TfWeakBaseProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"_TfWeakBaseProtocol"}],"abstract":[{"text":"Protocol representing ","type":"text"},{"type":"codeVoice","code":"pxr::TfWeakBase"},{"text":" subclasses. Don’t use this unless you know what you’re doing","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"_TfWeakBaseProtocol"}],"url":"\/documentation\/openusd\/c++\/overlay\/_tfweakbaseprotocol","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/Overlay\/_TfWeakBaseProtocol"},"doc://SwiftUsd/documentation/OpenUSD/RevokeAndWait-9e095":{"navigatorTitle":[{"kind":"identifier","text":"RevokeAndWait"}],"abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/revokeandwait-9e095","role":"symbol","type":"topic","title":"RevokeAndWait(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-9e095","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RevokeAndWait","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfNotice@S@SwiftKey#$@N@std@N@__1@S@allocator>#S0_","text":"SwiftKeys","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":")","kind":"text"}]},"doc://SwiftUsd/documentation/OpenUSD":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol","title":"OpenUSD","type":"topic","role":"collection","url":"\/documentation\/openusd"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:_:)-8j5mu":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Register"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Notice"},{"kind":"text","text":", "},{"kind":"genericParameter","text":"Sender"},{"kind":"text","text":">("},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyxYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp","text":"Sender"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyxYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","text":"Notice"},{"kind":"text","text":".Type, ("},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyxYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","text":"Notice"},{"kind":"text","text":") -> ()) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","text":"SwiftKey"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-8j5mu","abstract":[{"type":"text","text":"Register a listener as being interested in a TfNotice from a particular sender."}],"kind":"symbol","role":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-8j5mu","type":"topic","title":"Register(_:_:_:)"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"text":"Overlay","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","title":"Overlay","url":"\/documentation\/openusd\/overlay"},"doc://SwiftUsd/documentation/OpenUSD/C++":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++","kind":"symbol","title":"C++","abstract":[],"role":"collection","url":"\/documentation\/openusd\/c++"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:_:)-6we16":{"role":"symbol","title":"Register(_:_:_:)","type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-6we16","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"Sender","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Sender","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"text":", ","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"text":".Type, (","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"text":", ","kind":"text"},{"text":"Sender","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"text":") -> ()) -> ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-6we16","kind":"symbol","abstract":[{"type":"text","text":"Register a listener as being interested in a TfNotice from a particular sender."}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:_:)-7toj3":{"type":"topic","role":"symbol","title":"Register(_:_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"Sender","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Sender","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"text":", ","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"text":".Type, (","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"text":", ","kind":"text"},{"text":"borrowing","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"NoticeCaster","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV"},{"text":") -> ()) -> ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}],"url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-7toj3","abstract":[{"text":"Register a listener as being interested in a TfNotice from a particular sender.","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-7toj3","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice":{"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice","kind":"identifier"}],"role":"symbol","abstract":[],"title":"pxr.TfNotice","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice","kind":"symbol","navigatorTitle":[{"text":"TfNotice","kind":"identifier"}],"type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr":{"navigatorTitle":[{"text":"pxr","kind":"identifier"}],"url":"\/documentation\/openusd\/c++\/pxr","title":"pxr","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr","abstract":[],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Revoke-31sr0":{"url":"\/documentation\/openusd\/revoke-31sr0","role":"symbol","title":"Revoke(_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Revoke","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","text":"SwiftKey","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:b","text":"Bool","kind":"typeIdentifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-31sr0","navigatorTitle":[{"text":"Revoke","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:)-2cm0u":{"role":"symbol","type":"topic","abstract":[{"text":"Register a listener as being interested in a TfNotice, regardless of sender.","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-2cm0u","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:)-2cm0u","kind":"symbol","title":"Register(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Register"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Notice"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"Notice","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp"},{"kind":"text","text":".Type, ("},{"kind":"typeIdentifier","text":"Notice","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp"},{"kind":"text","text":", "},{"kind":"keyword","text":"borrowing"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"NoticeCaster","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV"},{"kind":"text","text":") -> ()) -> "},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"SwiftKey","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}]},"doc://SwiftUsd/documentation/OpenUSD/Revoke-2xoh5":{"url":"\/documentation\/openusd\/revoke-2xoh5","abstract":[],"title":"Revoke(_:)","type":"topic","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-2xoh5","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Revoke","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfNotice@S@SwiftKey#$@N@std@N@__1@S@allocator>#S0_","text":"SwiftKeys","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Revoke"}],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:_:)-17h9z":{"type":"topic","title":"Register(_:_:_:)","abstract":[{"type":"text","text":"Register a listener as being interested in a TfNotice from a particular sender."}],"url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-17h9z","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-17h9z","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"Sender","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Sender","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"text":", ","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"text":".Type, (","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"text":", ","kind":"text"},{"text":"Sender","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"text":", ","kind":"text"},{"text":"borrowing","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"NoticeCaster","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV"},{"text":") -> ()) -> ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/SwiftUsd/TfNoticeProtocol":{"url":"\/documentation\/openusd\/c++\/swiftusd\/tfnoticeprotocol","abstract":[{"type":"text","text":"Protocol representing "},{"type":"codeVoice","code":"pxr::TfNotice"},{"type":"text","text":" subclasses."}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/SwiftUsd\/TfNoticeProtocol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TfNoticeProtocol"}],"title":"SwiftUsd.TfNoticeProtocol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TfNoticeProtocol"}]},"doc://SwiftUsd/documentation/OpenUSD/SwiftUsd":{"url":"\/documentation\/openusd\/swiftusd","role":"symbol","title":"SwiftUsd","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftUsd","fragments":[{"kind":"identifier","text":"SwiftUsd"}]},"doc://SwiftUsd/documentation/OpenUSD/SwiftKey":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SwiftKey","kind":"identifier"}],"navigatorTitle":[{"text":"SwiftKey","kind":"identifier"}],"title":"class SwiftKey","url":"\/documentation\/openusd\/swiftkey","abstract":[{"text":"A key representing a listener registered from either Swift or C++","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-7ycue\/title","value":"RevokeAndWait","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-7ycue\/fragments","value":[{"kind":"identifier","text":"RevokeAndWait"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-7ycue\/navigatorTitle","value":[{"kind":"identifier","text":"RevokeAndWait"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-9e095\/title","value":"RevokeAndWait","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-9e095\/fragments","value":[{"text":"RevokeAndWait","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-9e095\/navigatorTitle","value":[{"kind":"identifier","text":"RevokeAndWait"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"kind":"identifier","text":"Overlay"}],"op":"add"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-31sr0\/title","value":"Revoke","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-31sr0\/fragments","value":[{"text":"Revoke","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-31sr0\/navigatorTitle","value":[{"kind":"identifier","text":"Revoke"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-2xoh5\/title","value":"Revoke","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-2xoh5\/fragments","value":[{"text":"Revoke","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-2xoh5\/navigatorTitle","value":[{"kind":"identifier","text":"Revoke"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/title","value":"SwiftUsd","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/fragments","value":[{"text":"SwiftUsd","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftUsd\/navigatorTitle","value":[{"kind":"identifier","text":"SwiftUsd"}],"op":"add"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/title","value":"SwiftKey","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/fragments","value":[{"kind":"identifier","text":"SwiftKey"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/navigatorTitle","value":[{"text":"SwiftKey","kind":"identifier"}],"op":"replace"}]}]}