{"sections":[],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/IntersectionResult"]]},"kind":"symbol","metadata":{"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"OpenUSD"}],"externalID":"c:@N@Overlay@S@UsdImagingGLEngineWrapper@S@IntersectionResult@FI@hitNormal","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hitNormal","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@GfVec3d","text":"GfVec3d","kind":"typeIdentifier"}],"title":"hitNormal","navigatorTitle":[{"text":"hitNormal","kind":"identifier"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/intersectionresult\/hitnormal"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/intersectionresult\/hitnormal"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/IntersectionResult\/hitNormal","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hitNormal","kind":"identifier"},{"text":": ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"GfVec3d","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@GfVec3d"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/IntersectionResult":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/IntersectionResult","title":"struct IntersectionResult","navigatorTitle":[{"kind":"identifier","text":"IntersectionResult"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntersectionResult"}],"type":"topic","role":"symbol","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/intersectionresult","abstract":[],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/IntersectionResult/hitNormal":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/IntersectionResult\/hitNormal","title":"hitNormal","navigatorTitle":[{"text":"hitNormal","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hitNormal","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@GfVec3d","text":"GfVec3d","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/intersectionresult\/hitnormal","abstract":[],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"text":"Overlay","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","title":"Overlay","url":"\/documentation\/openusd\/overlay"},"doc://SwiftUsd/documentation/OpenUSD":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol","title":"OpenUSD","type":"topic","role":"collection","url":"\/documentation\/openusd"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper":{"url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","title":"class UsdImagingGLEngineWrapper","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"hitNormal","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"hitNormal"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"hitNormal","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@GfVec3d","text":"GfVec3d"},{"kind":"text","text":" "},{"kind":"identifier","text":"hitNormal"},{"kind":"text","text":";"}],"platforms":["macOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1IntersectionResult\/title","value":"IntersectionResult","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1IntersectionResult\/fragments","value":[{"text":"IntersectionResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1IntersectionResult\/navigatorTitle","value":[{"text":"IntersectionResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1IntersectionResult~1hitNormal\/title","value":"hitNormal","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1IntersectionResult~1hitNormal\/fragments","value":[{"kind":"identifier","text":"hitNormal"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1IntersectionResult~1hitNormal\/navigatorTitle","value":[{"text":"hitNormal","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"text":"Overlay","kind":"identifier"}],"op":"add"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/title","value":"UsdImagingGLEngineWrapper","op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/fragments","value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/navigatorTitle","value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"op":"replace"}]}]}