{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SetIncludedPurposes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"purposes"},{"kind":"text","text":": "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfToken#$@N@std@N@__1@S@allocator>#S0_","kind":"typeIdentifier","text":"TfTokenVector"},{"kind":"text","text":")"}]}]}],"sections":[],"variants":[{"paths":["\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper\/setincludedpurposes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper\/setincludedpurposes"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper\/SetIncludedPurposes","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"OpenUSD"}],"navigatorTitle":[{"kind":"identifier","text":"SetIncludedPurposes"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SetIncludedPurposes"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfToken#$@N@std@N@__1@S@allocator>#S0_","text":"TfTokenVector"},{"kind":"text","text":")"}],"externalID":"c:@N@Overlay@S@UsdAppUtilsFrameRecorderWrapper@F@SetIncludedPurposes#&1$@N@std@N@__1@S@vector>#$@N@pxr@S@TfToken#$@N@std@N@__1@S@allocator>#S2_#","title":"SetIncludedPurposes(_:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper"]]},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdAppUtilsFrameRecorderWrapper/SetIncludedPurposes":{"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SetIncludedPurposes","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper\/setincludedpurposes","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper\/SetIncludedPurposes","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SetIncludedPurposes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"TfTokenVector","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfToken#$@N@std@N@__1@S@allocator>#S0_"},{"text":")","kind":"text"}],"title":"SetIncludedPurposes(_:)"},"doc://SwiftUsd/documentation/OpenUSD":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol","title":"OpenUSD","type":"topic","role":"collection","url":"\/documentation\/openusd"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"text":"Overlay","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","title":"Overlay","url":"\/documentation\/openusd\/overlay"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdAppUtilsFrameRecorderWrapper":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdAppUtilsFrameRecorderWrapper","kind":"symbol","type":"topic","url":"\/documentation\/openusd\/overlay\/usdapputilsframerecorderwrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdAppUtilsFrameRecorderWrapper"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UsdAppUtilsFrameRecorderWrapper"}],"title":"class UsdAppUtilsFrameRecorderWrapper"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"SetIncludedPurposes"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SetIncludedPurposes"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SetIncludedPurposes","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SetIncludedPurposes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":"::","kind":"text"},{"text":"TfTokenVector","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfToken#$@N@std@N@__1@S@allocator>#S0_","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"text":"purposes","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["macOS"]}]}},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper~1SetIncludedPurposes\/title","op":"replace","value":"SetIncludedPurposes"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper~1SetIncludedPurposes\/fragments","op":"replace","value":[{"kind":"identifier","text":"SetIncludedPurposes"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper~1SetIncludedPurposes\/navigatorTitle","op":"replace","value":[{"text":"SetIncludedPurposes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","op":"replace","value":"Overlay"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","op":"replace","value":[{"text":"Overlay","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","op":"add","value":[{"kind":"identifier","text":"Overlay"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/title","op":"replace","value":"UsdAppUtilsFrameRecorderWrapper"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/fragments","op":"replace","value":[{"kind":"identifier","text":"UsdAppUtilsFrameRecorderWrapper"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdAppUtilsFrameRecorderWrapper\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UsdAppUtilsFrameRecorderWrapper"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}