{"kind":"symbol","abstract":[{"type":"text","text":"Returns "},{"code":"true","type":"codeVoice"},{"type":"text","text":" if the "},{"code":"HioImage","type":"codeVoice"},{"type":"text","text":" is valid"}],"variants":[{"paths":["\/documentation\/openusd\/swift\/bool\/init(_:)-1tb4n"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"x","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","preciseIdentifier":"c:@N@Overlay","text":"Overlay","kind":"typeIdentifier"},{"text":".","kind":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","preciseIdentifier":"c:@N@Overlay@S@HioImageWrapper","text":"HioImageWrapper","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift\/Bool\/init(_:)-1tb4n","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift\/Bool"]]},"metadata":{"modules":[{"name":"OpenUSD","relatedModules":["Swift"]}],"extendedModule":"Swift","roleHeading":"Initializer","title":"init(_:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@Overlay","text":"Overlay","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@Overlay@S@HioImageWrapper","text":"HioImageWrapper","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"s:Sb7OpenUSDEySbSo7OverlayO15HioImageWrapperVcfc","role":"symbol","symbolKind":"init"},"references":{"doc://SwiftUsd/documentation/OpenUSD":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol","title":"OpenUSD","type":"topic","role":"collection","url":"\/documentation\/openusd"},"doc://SwiftUsd/documentation/OpenUSD/Swift":{"type":"topic","role":"collection","title":"Swift","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift","url":"\/documentation\/openusd\/swift","abstract":[],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Swift/Bool":{"type":"topic","role":"symbol","title":"Bool","navigatorTitle":[{"kind":"identifier","text":"Bool"}],"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift\/Bool","url":"\/documentation\/openusd\/swift\/bool","abstract":[],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Swift/Bool/init(_:)-1tb4n":{"url":"\/documentation\/openusd\/swift\/bool\/init(_:)-1tb4n","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@Overlay","text":"Overlay","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@Overlay@S@HioImageWrapper","text":"HioImageWrapper","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(_:)","type":"topic","abstract":[{"text":"Returns ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if the ","type":"text"},{"code":"HioImage","type":"codeVoice"},{"text":" is valid","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Swift\/Bool\/init(_:)-1tb4n","role":"symbol","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HioImageWrapper"}],"title":"class HioImageWrapper","abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/hioimagewrapper","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HioImageWrapper"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"fragments":[{"text":"Overlay","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","abstract":[{"text":"The namespace used to group workarounds to limitations in Swift-Cxx interop","type":"text"}],"role":"symbol","title":"Overlay","url":"\/documentation\/openusd\/overlay"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/title","op":"replace","value":"HioImageWrapper"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/fragments","op":"replace","value":[{"text":"HioImageWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"HioImageWrapper"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","op":"replace","value":"Overlay"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","op":"replace","value":[{"kind":"identifier","text":"Overlay"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","op":"add","value":[{"kind":"identifier","text":"Overlay"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}