{"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper"]]},"sections":[],"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@N@Overlay@S@UsdImagingGLEngineWrapper@F@SetRendererAovs#&1$@N@std@N@__1@S@vector>#$@N@pxr@S@TfToken#$@N@std@N@__1@S@allocator>#S2_#","modules":[{"name":"OpenUSD"}],"fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SetRendererAovs","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfToken#$@N@std@N@__1@S@allocator>#S0_","text":"TfTokenVector","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:b","text":"Bool","kind":"typeIdentifier"}],"title":"SetRendererAovs(_:)","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"SetRendererAovs","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/setrendereraovs"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/setrendereraovs"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SetRendererAovs","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"ids","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"TfTokenVector","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfToken#$@N@std@N@__1@S@allocator>#S0_"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/SetRendererAovs"},"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/SetRendererAovs":{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/SetRendererAovs","title":"SetRendererAovs(_:)","navigatorTitle":[{"kind":"identifier","text":"SetRendererAovs"}],"role":"symbol","type":"topic","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SetRendererAovs","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfToken#$@N@std@N@__1@S@allocator>#S0_","text":"TfTokenVector","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:b","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/setrendereraovs","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper":{"abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper","navigatorTitle":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","title":"class UsdImagingGLEngineWrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"role":"symbol","abstract":[{"type":"text","text":"The namespace used to group workarounds to limitations in Swift-Cxx interop"}],"url":"\/documentation\/openusd\/overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","type":"topic","fragments":[{"text":"Overlay","kind":"identifier"}],"title":"Overlay","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"SetRendererAovs"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SetRendererAovs"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SetRendererAovs","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"bool","kind":"typeIdentifier","preciseIdentifier":"c:b"},{"text":" ","kind":"text"},{"text":"SetRendererAovs","kind":"identifier"},{"text":"(","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":"::","kind":"text"},{"text":"TfTokenVector","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfToken#$@N@std@N@__1@S@allocator>#S0_"},{"text":" & ","kind":"text"},{"text":"ids","kind":"internalParam"},{"text":");","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1SetRendererAovs\/title","value":"SetRendererAovs"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1SetRendererAovs\/fragments","value":[{"kind":"identifier","text":"SetRendererAovs"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1SetRendererAovs\/navigatorTitle","value":[{"text":"SetRendererAovs","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/title","value":"UsdImagingGLEngineWrapper"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/fragments","value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"text":"Overlay","kind":"identifier"}]},{"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"text":"Overlay","kind":"identifier"}]}]}]}