{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SetRendererSetting","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"id","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfToken","text":"TfToken","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"value","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@VtValue","text":"VtValue","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper"]]},"metadata":{"roleHeading":"Instance Method","externalID":"c:@N@Overlay@S@UsdImagingGLEngineWrapper@F@SetRendererSetting#&1$@N@pxr@S@TfToken#&1$@N@pxr@S@VtValue#","fragments":[{"text":"mutating","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SetRendererSetting","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfToken","text":"TfToken","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@VtValue","text":"VtValue","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"OpenUSD"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"SetRendererSetting"}],"title":"SetRendererSetting(_:_:)"},"variants":[{"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/setrenderersetting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/setrenderersetting"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/SetRendererSetting","interfaceLanguage":"swift"},"sections":[],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper":{"abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper","navigatorTitle":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper","title":"class UsdImagingGLEngineWrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}]},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection"},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"role":"symbol","abstract":[{"type":"text","text":"The namespace used to group workarounds to limitations in Swift-Cxx interop"}],"url":"\/documentation\/openusd\/overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","type":"topic","fragments":[{"text":"Overlay","kind":"identifier"}],"title":"Overlay","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdImagingGLEngineWrapper/SetRendererSetting":{"url":"\/documentation\/openusd\/overlay\/usdimagingglenginewrapper\/setrenderersetting","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdImagingGLEngineWrapper\/SetRendererSetting","type":"topic","kind":"symbol","title":"SetRendererSetting(_:_:)","role":"symbol","fragments":[{"kind":"keyword","text":"mutating"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SetRendererSetting"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfToken","text":"TfToken"},{"kind":"text","text":", "},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"VtValue","preciseIdentifier":"c:@N@pxr@S@VtValue"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"SetRendererSetting"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SetRendererSetting","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SetRendererSetting","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SetRendererSetting","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" "},{"kind":"identifier","text":"SetRendererSetting"},{"kind":"text","text":"("},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","text":"TfToken","preciseIdentifier":"c:@N@pxr@S@TfToken"},{"kind":"text","text":" & "},{"kind":"internalParam","text":"id"},{"kind":"text","text":", "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","text":"VtValue","preciseIdentifier":"c:@N@pxr@S@VtValue"},{"kind":"text","text":" & "},{"kind":"internalParam","text":"value"},{"kind":"text","text":");"}],"platforms":["macOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"UsdImagingGLEngineWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/title"},{"op":"replace","value":[{"kind":"identifier","text":"UsdImagingGLEngineWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/fragments"},{"op":"replace","value":[{"text":"UsdImagingGLEngineWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper\/navigatorTitle"},{"op":"replace","value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"op":"add","value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"op":"replace","value":"SetRendererSetting","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1SetRendererSetting\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SetRendererSetting"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1SetRendererSetting\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SetRendererSetting"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdImagingGLEngineWrapper~1SetRendererSetting\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}