{"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetBytesPerPixel"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/getbytesperpixel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/getbytesperpixel"]}],"metadata":{"role":"symbol","externalID":"c:@N@Overlay@S@HioImageWrapper@F@GetBytesPerPixel#1","navigatorTitle":[{"text":"GetBytesPerPixel","kind":"identifier"}],"title":"GetBytesPerPixel()","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"OpenUSD"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetBytesPerPixel","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"CInt","preciseIdentifier":"c:I","kind":"typeIdentifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetBytesPerPixel","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"CInt","kind":"typeIdentifier","preciseIdentifier":"c:I"}]}]}],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"role":"symbol","abstract":[{"type":"text","text":"The namespace used to group workarounds to limitations in Swift-Cxx interop"}],"url":"\/documentation\/openusd\/overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","type":"topic","fragments":[{"text":"Overlay","kind":"identifier"}],"title":"Overlay","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/GetBytesPerPixel":{"abstract":[],"role":"symbol","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/getbytesperpixel","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/GetBytesPerPixel","title":"GetBytesPerPixel()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetBytesPerPixel","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"CInt","kind":"typeIdentifier","preciseIdentifier":"c:I"}],"type":"topic","navigatorTitle":[{"text":"GetBytesPerPixel","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper":{"kind":"symbol","url":"\/documentation\/openusd\/overlay\/hioimagewrapper","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","navigatorTitle":[{"kind":"identifier","text":"HioImageWrapper"}],"role":"symbol","type":"topic","title":"class HioImageWrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HioImageWrapper"}]},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"GetBytesPerPixel","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"GetBytesPerPixel"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"GetBytesPerPixel","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetBytesPerPixel"},{"kind":"text","text":"() "},{"kind":"keyword","text":"const"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"op":"add","value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"op":"replace","value":"GetBytesPerPixel","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetBytesPerPixel\/title"},{"op":"replace","value":[{"text":"GetBytesPerPixel","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetBytesPerPixel\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GetBytesPerPixel"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1GetBytesPerPixel\/navigatorTitle"},{"op":"replace","value":"HioImageWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/title"},{"op":"replace","value":[{"text":"HioImageWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"HioImageWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/navigatorTitle"}]}]}