{"kind":"symbol","metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IsColorSpaceSRGB","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"}],"externalID":"c:@N@Overlay@S@HioImageWrapper@F@IsColorSpaceSRGB#1","title":"IsColorSpaceSRGB()","navigatorTitle":[{"text":"IsColorSpaceSRGB","kind":"identifier"}],"role":"symbol","modules":[{"name":"OpenUSD"}],"symbolKind":"method"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"IsColorSpaceSRGB"},{"kind":"text","text":"()"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:b","text":"Bool"}],"platforms":["macOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/IsColorSpaceSRGB","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/iscolorspacesrgb"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/overlay\/hioimagewrapper\/iscolorspacesrgb"]}],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper":{"kind":"symbol","url":"\/documentation\/openusd\/overlay\/hioimagewrapper","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper","navigatorTitle":[{"kind":"identifier","text":"HioImageWrapper"}],"role":"symbol","type":"topic","title":"class HioImageWrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HioImageWrapper"}]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"role":"symbol","abstract":[{"type":"text","text":"The namespace used to group workarounds to limitations in Swift-Cxx interop"}],"url":"\/documentation\/openusd\/overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","type":"topic","fragments":[{"text":"Overlay","kind":"identifier"}],"title":"Overlay","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/HioImageWrapper/IsColorSpaceSRGB":{"title":"IsColorSpaceSRGB()","kind":"symbol","url":"\/documentation\/openusd\/overlay\/hioimagewrapper\/iscolorspacesrgb","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/HioImageWrapper\/IsColorSpaceSRGB","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IsColorSpaceSRGB","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:b","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"IsColorSpaceSRGB","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"IsColorSpaceSRGB"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"IsColorSpaceSRGB","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"IsColorSpaceSRGB","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"bool","kind":"typeIdentifier","preciseIdentifier":"c:b"},{"text":" ","kind":"text"},{"text":"IsColorSpaceSRGB","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"const","kind":"keyword"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/title","value":"HioImageWrapper"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/fragments","value":[{"text":"HioImageWrapper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper\/navigatorTitle","value":[{"text":"HioImageWrapper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","value":"Overlay"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","value":[{"kind":"identifier","text":"Overlay"}]},{"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","value":[{"kind":"identifier","text":"Overlay"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1IsColorSpaceSRGB\/title","value":"IsColorSpaceSRGB"},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1IsColorSpaceSRGB\/fragments","value":[{"kind":"identifier","text":"IsColorSpaceSRGB"}]},{"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1HioImageWrapper~1IsColorSpaceSRGB\/navigatorTitle","value":[{"kind":"identifier","text":"IsColorSpaceSRGB"}]}]}]}