{"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-2xoh5","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openusd\/revoke-2xoh5"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/openusd\/revoke-2xoh5"]}],"metadata":{"externalID":"c:@N@pxr@S@TfNotice@F@Revoke#*$@N@std@N@__1@S@vector>#$@N@pxr@S@TfNotice@S@SwiftKey#$@N@std@N@__1@S@allocator>#S2_#S","navigatorTitle":[{"text":"Revoke","kind":"identifier"}],"roleHeading":"Static Method","symbolKind":"method","modules":[{"name":"OpenUSD"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Revoke","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":".","kind":"text"},{"text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"SwiftKeys","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfNotice@S@SwiftKey#$@N@std@N@__1@S@allocator>#S0_","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":")","kind":"text"}],"role":"symbol","title":"Revoke(_:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Revoke"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"keys"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"SwiftKeys","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfNotice@S@SwiftKey#$@N@std@N@__1@S@allocator>#S0_"},{"kind":"text","text":">"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-99j13","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-8j5mu","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-6we16","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-2cm0u","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-7toj3","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-17h9z","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-31sr0","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-7ycue","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-9e095"],"generated":true,"title":"Type Methods","anchor":"Type-Methods"}],"sections":[],"kind":"symbol","references":{"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:_:)-8j5mu":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Register"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Notice"},{"kind":"text","text":", "},{"kind":"genericParameter","text":"Sender"},{"kind":"text","text":">("},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyxYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp","text":"Sender"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyxYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","text":"Notice"},{"kind":"text","text":".Type, ("},{"kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyxYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp","text":"Notice"},{"kind":"text","text":") -> ()) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","text":"SwiftKey"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-8j5mu","abstract":[{"type":"text","text":"Register a listener as being interested in a TfNotice from a particular sender."}],"kind":"symbol","role":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-8j5mu","type":"topic","title":"Register(_:_:_:)"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:_:)-6we16":{"role":"symbol","title":"Register(_:_:_:)","type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-6we16","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"Sender","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Sender","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"text":", ","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"text":".Type, (","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"text":", ","kind":"text"},{"text":"Sender","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_tYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseM0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"text":") -> ()) -> ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-6we16","kind":"symbol","abstract":[{"type":"text","text":"Register a listener as being interested in a TfNotice from a particular sender."}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:)-2cm0u":{"role":"symbol","type":"topic","abstract":[{"text":"Register a listener as being interested in a TfNotice, regardless of sender.","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-2cm0u","url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:)-2cm0u","kind":"symbol","title":"Register(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Register"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Notice"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"Notice","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp"},{"kind":"text","text":".Type, ("},{"kind":"typeIdentifier","text":"Notice","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp"},{"kind":"text","text":", "},{"kind":"keyword","text":"borrowing"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"NoticeCaster","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV"},{"kind":"text","text":") -> ()) -> "},{"kind":"typeIdentifier","text":"pxr","preciseIdentifier":"s:7OpenUSD3pxra"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"TfNotice","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"SwiftKey","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}]},"doc://SwiftUsd/documentation/OpenUSD/Revoke-31sr0":{"url":"\/documentation\/openusd\/revoke-31sr0","role":"symbol","title":"Revoke(_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Revoke","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey","text":"SwiftKey","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:b","text":"Bool","kind":"typeIdentifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-31sr0","navigatorTitle":[{"text":"Revoke","kind":"identifier"}]},"doc://SwiftUsd/documentation/OpenUSD/RevokeAndWait-9e095":{"navigatorTitle":[{"kind":"identifier","text":"RevokeAndWait"}],"abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/revokeandwait-9e095","role":"symbol","type":"topic","title":"RevokeAndWait(_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-9e095","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RevokeAndWait","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfNotice@S@SwiftKey#$@N@std@N@__1@S@allocator>#S0_","text":"SwiftKeys","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":")","kind":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/Revoke-2xoh5":{"url":"\/documentation\/openusd\/revoke-2xoh5","abstract":[],"title":"Revoke(_:)","type":"topic","kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-2xoh5","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Revoke","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@N@pxr","text":"pxr","kind":"identifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfNotice@S@SwiftKey#$@N@std@N@__1@S@allocator>#S0_","text":"SwiftKeys","kind":"typeIdentifier"},{"text":">","kind":"text"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Revoke"}],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:)-99j13":{"kind":"symbol","role":"symbol","title":"Register(_:_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yxYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp"},{"text":".Type, (","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVxm_yxYbctSo0J3UsdOAEE0eF8ProtocolRzlFZ0F0L_xmfp"},{"text":") -> ()) -> ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}],"abstract":[{"text":"Register a listener as being interested in a TfNotice, regardless of sender.","type":"text"}],"url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:)-99j13","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:)-99j13"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:_:)-7toj3":{"type":"topic","role":"symbol","title":"Register(_:_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"Sender","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Sender","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"text":", ","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"text":".Type, (","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"text":", ","kind":"text"},{"text":"borrowing","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"NoticeCaster","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV"},{"text":") -> ()) -> ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}],"url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-7toj3","abstract":[{"text":"Register a listener as being interested in a TfNotice from a particular sender.","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-7toj3","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD":{"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","kind":"symbol","title":"OpenUSD","type":"topic","role":"collection","url":"\/documentation\/openusd"},"doc://SwiftUsd/documentation/OpenUSD/RevokeAndWait-7ycue":{"abstract":[],"kind":"symbol","type":"topic","title":"RevokeAndWait(_:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RevokeAndWait","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"}],"navigatorTitle":[{"text":"RevokeAndWait","kind":"identifier"}],"url":"\/documentation\/openusd\/revokeandwait-7ycue","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-7ycue"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/TfNotice/Register(_:_:_:)-17h9z":{"type":"topic","title":"Register(_:_:_:)","abstract":[{"type":"text","text":"Register a listener as being interested in a TfNotice from a particular sender."}],"url":"\/documentation\/openusd\/c++\/pxr\/tfnotice\/register(_:_:_:)-17h9z","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/TfNotice\/Register(_:_:_:)-17h9z","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Register","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Notice","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"Sender","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"Sender","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"text":", ","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"text":".Type, (","kind":"text"},{"text":"Notice","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ0F0L_xmfp"},{"text":", ","kind":"text"},{"text":"Sender","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE8RegisteryAD8SwiftKeyVq__xmyx_q_AdEE0F6CasterVtYbctSo0J3UsdOAEE0eF8ProtocolRzSo7OverlayOAEE01_e8WeakBaseN0R_9_SelfTypeQy_Rs_r0_lFZ6SenderL_q_mfp"},{"text":", ","kind":"text"},{"text":"borrowing","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"NoticeCaster","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O8TfNoticeV7OpenUSDE0F6CasterV"},{"text":") -> ()) -> ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfNotice","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice"},{"text":".","kind":"text"},{"text":"SwiftKey","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice@S@SwiftKey"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Static Method"},{"path":"\/metadata\/title","op":"replace","value":"Revoke"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"Revoke"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"Revoke","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Revoke-31sr0","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-7ycue","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/RevokeAndWait-9e095"],"title":"Type Methods","anchor":"Type-Methods","generated":true}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" "},{"kind":"identifier","text":"Revoke"},{"kind":"text","text":"("},{"kind":"identifier","preciseIdentifier":"c:@N@pxr","text":"pxr"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfNotice","text":"TfNotice"},{"kind":"text","text":"::"},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@vector>#$@N@pxr@S@TfNotice@S@SwiftKey#$@N@std@N@__1@S@allocator>#S0_","text":"SwiftKeys"},{"text":" * ","kind":"text"},{"text":"keys","kind":"internalParam"},{"text":");","kind":"text"}],"languages":["occ"],"platforms":["macOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-31sr0\/title","op":"replace","value":"Revoke"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-31sr0\/fragments","op":"replace","value":[{"kind":"identifier","text":"Revoke"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-31sr0\/navigatorTitle","op":"replace","value":[{"text":"Revoke","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-9e095\/title","op":"replace","value":"RevokeAndWait"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-9e095\/fragments","op":"replace","value":[{"kind":"identifier","text":"RevokeAndWait"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-9e095\/navigatorTitle","op":"replace","value":[{"text":"RevokeAndWait","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-2xoh5\/title","op":"replace","value":"Revoke"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-2xoh5\/fragments","op":"replace","value":[{"text":"Revoke","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Revoke-2xoh5\/navigatorTitle","op":"replace","value":[{"text":"Revoke","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-7ycue\/title","op":"replace","value":"RevokeAndWait"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-7ycue\/fragments","op":"replace","value":[{"kind":"identifier","text":"RevokeAndWait"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1RevokeAndWait-7ycue\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"RevokeAndWait"}]}]}]}