{"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UsdPrimTypeInfoWrapper","kind":"typeIdentifier","preciseIdentifier":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper"},{"text":", ","kind":"text"},{"text":"UsdPrimTypeInfoWrapper","kind":"typeIdentifier","preciseIdentifier":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"}],"symbolKind":"op","title":"!=(_:_:)","navigatorTitle":[{"text":"operator!=","kind":"identifier"}],"roleHeading":"Operator","modules":[{"name":"OpenUSD"}],"role":"symbol","externalID":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper@F@operator!=#&1$@N@Overlay@S@UsdPrimTypeInfoWrapper#1"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/operator!="},"sections":[],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/operator!="],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/operator!="],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":": ","kind":"text"},{"text":"UsdPrimTypeInfoWrapper","kind":"typeIdentifier","preciseIdentifier":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"other","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UsdPrimTypeInfoWrapper","kind":"typeIdentifier","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","preciseIdentifier":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"type":"topic","role":"symbol","title":"struct UsdPrimTypeInfoWrapper","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay/UsdPrimTypeInfoWrapper/operator!=":{"navigatorTitle":[{"text":"operator!=","kind":"identifier"}],"title":"!=(_:_:)","url":"\/documentation\/openusd\/overlay\/usdprimtypeinfowrapper\/operator!=","type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UsdPrimTypeInfoWrapper","preciseIdentifier":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"UsdPrimTypeInfoWrapper","preciseIdentifier":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper","kind":"typeIdentifier"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper\/operator!=","role":"symbol","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"role":"symbol","abstract":[{"type":"text","text":"The namespace used to group workarounds to limitations in Swift-Cxx interop"}],"url":"\/documentation\/openusd\/overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","type":"topic","fragments":[{"text":"Overlay","kind":"identifier"}],"title":"Overlay","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"operator!=","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"operator!="}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"operator!=","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"text":"bool","preciseIdentifier":"c:b","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"operator!=","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/UsdPrimTypeInfoWrapper","preciseIdentifier":"c:@N@Overlay@S@UsdPrimTypeInfoWrapper","text":"UsdPrimTypeInfoWrapper"},{"kind":"text","text":" & "},{"kind":"internalParam","text":"other"},{"kind":"text","text":") "},{"kind":"keyword","text":"const"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"UsdPrimTypeInfoWrapper","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/title","op":"replace"},{"value":[{"text":"UsdPrimTypeInfoWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UsdPrimTypeInfoWrapper"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper\/navigatorTitle","op":"replace"},{"value":"operator!=","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1operator!=\/title","op":"replace"},{"value":[{"text":"operator!=","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1operator!=\/fragments","op":"replace"},{"value":[{"text":"operator!=","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1UsdPrimTypeInfoWrapper~1operator!=\/navigatorTitle","op":"replace"},{"value":"Overlay","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title","op":"replace"},{"value":[{"text":"Overlay","kind":"identifier"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Overlay"}],"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle","op":"add"}],"traits":[{"interfaceLanguage":"occ"}]}]}