{"metadata":{"role":"article","modules":[{"name":"OpenUSD"}],"roleHeading":"Article","title":"Getting Started with OpenUSD"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Adding SwiftUsd to your project or package","type":"text"}],"seeAlsoSections":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Capabilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DifferencesInSwift","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CurrentLimitations"],"anchor":"Essentials","title":"Essentials","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/GettingStarted"},"sections":[],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftusd\/gettingstarted"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/swiftusd\/gettingstarted"]}],"kind":"article","primaryContentSections":[{"content":[{"text":"Getting Started","anchor":"Getting-Started","level":2,"type":"heading"},{"inlineContent":[{"text":"Before you can start using SwiftUsd, you need to add it as a dependency to your Xcode project or Swift Package, and then configure a few build settings.","type":"text"}],"type":"paragraph"},{"name":"Important","style":"important","content":[{"inlineContent":[{"type":"text","text":"Tested with OpenUSD v25.08, Xcode 26.1.1 (17B100) on macOS 15.6 (24G84), iPadOS 26.0 (23A341), and visionOS 26.1 (23N49)."}],"type":"paragraph"}],"type":"aside"},{"text":"Xcode project","anchor":"Xcode-project","level":3,"type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"To use SwiftUsd in an Xcode project, select File > Add Package Dependencies…, and enter the following URL:","type":"text"}]}]}],"type":"orderedList"},{"code":["https:\/\/github.com\/apple\/SwiftUsd"],"syntax":null,"type":"codeListing"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"In the build settings for your target, set "},{"type":"codeVoice","code":"C++ and Objective-C Interoperability"},{"type":"text","text":" to "},{"type":"codeVoice","code":"C++ \/ Objective-C++"},{"type":"text","text":" ("},{"type":"codeVoice","code":"SWIFT_OBJC_INTEROP_MODE=objcxx"},{"type":"text","text":")."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"In the build settings for your target, set "},{"code":"C++ Language Dialect","type":"codeVoice"},{"type":"text","text":" to "},{"code":"GNU++17 [-std=gnu++17]","type":"codeVoice"},{"type":"text","text":" ("},{"code":"CLANG_CXX_LANGUAGE_STANDARD=gnu++17","type":"codeVoice"},{"type":"text","text":")."}],"type":"paragraph"}]}],"start":2,"type":"orderedList"},{"name":"Note","style":"note","content":[{"inlineContent":[{"type":"text","text":"For command line tools, you may need to set "},{"type":"codeVoice","code":"Runpath Search Paths"},{"type":"text","text":" to "},{"type":"codeVoice","code":"@executable_path\/Frameworks"},{"type":"text","text":" ("},{"type":"codeVoice","code":"LD_RUNPATH_SEARCH_PATHS=@executable_path\/Frameworks"},{"type":"text","text":"), due to "},{"type":"reference","identifier":"rdar:\/\/138337998","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"type":"aside"},{"text":"Swift Package","anchor":"Swift-Package","level":3,"type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"To use SwiftUsd in a Swift Package, first add it as a dependency:"}]}]}],"type":"orderedList"},{"code":["dependencies: [","    .package(url: \"https:\/\/github.com\/apple\/SwiftUsd\", from: \"5.2.0\"),","]"],"syntax":"swift","type":"codeListing"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Then enable Swift-Cxx interoperability on your Swift targets:"}],"type":"paragraph"}]}],"start":2,"type":"orderedList"},{"code":[".target(name: \"MyTarget\",","        dependencies: [.product(name: \"OpenUSD\", package: \"SwiftUsd\")],","        swiftSettings: [","            .interoperabilityMode(.Cxx)","        ]),"],"syntax":"swift","type":"codeListing"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Then set the C++ language standard to GNU++17:"}],"type":"paragraph"}]}],"start":3,"type":"orderedList"},{"code":["let package = Package(","    name: \"MyPackage\",","    targets: [...],","    cxxLanguageStandard: .gnucxx17",")"],"syntax":"swift","type":"codeListing"},{"text":"Using SwiftUsd","anchor":"Using-SwiftUsd","level":3,"type":"heading"},{"inlineContent":[{"text":"Once you’ve added SwiftUsd as a package depedency to your Xcode project or Swift Package, enabled Swift-Cxx interop, and set the C++ version to GNU++17, you’re ready to start using SwiftUsd:","type":"text"}],"type":"paragraph"},{"code":["import OpenUSD","","public typealias pxr = pxrInternal_v0_25_8__pxrReserved__","","func makeHelloWorldString() -> String {","    let stage = Overlay.Dereference(pxr.UsdStage.CreateInMemory())","    stage.DefinePrim(\"\/hello\", .UsdGeomTokens.Xform)","    stage.DefinePrim(\"\/hello\/world\", .UsdGeomTokens.Sphere)","    return stage.ExportToString() ?? \"nil\"","}","print(makeHelloWorldString())"],"syntax":"swift","type":"codeListing"},{"name":"Warning","style":"warning","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"When working in Swift, do not use "},{"type":"codeVoice","code":"TfRefPtr.pointee"},{"type":"text","text":" or "},{"type":"codeVoice","code":"TfWeakPtr.pointee"},{"type":"text","text":", as they are unsafe. Use "},{"type":"codeVoice","code":"Overlay.Dereference(_:TfRefPtr)"},{"type":"text","text":" and "},{"type":"codeVoice","code":"Overlay.Dereference(_:TfWeakPtr)"},{"type":"text","text":" instead."}]}],"type":"aside"},{"text":"Common issues","anchor":"Common-issues","level":3,"type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Building fails with "},{"code":"Cannot load underlying module for 'CxxStdlib'","type":"codeVoice"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"strong","inlineContent":[{"type":"text","text":"Solution"}]},{"type":"text","text":": In the Build Settings for your target, make sure that “C++ and Objective-C Interoperability” is set to “C++ and Objective-C++”. ("},{"code":"SWIFT_OBJC_INTEROP_MODE=objcxx","type":"codeVoice"},{"type":"text","text":" for xcconfig files.)"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Building fails with "},{"type":"codeVoice","code":"Use of undeclared identifier '\\_LIBCPP\\_ASSERT'"},{"type":"text","text":" or "},{"type":"codeVoice","code":"Could not build Objective-C module '\\_OpenUSD\\_SwiftBindingHelpers"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"strong","inlineContent":[{"text":"Solution","type":"text"}]},{"type":"text","text":": In the Build Settings for your target, make sure that "},{"type":"codeVoice","code":"C++ Language Dialect"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"GNU++17 [-std=gnu++17]"},{"type":"text","text":". ("},{"type":"codeVoice","code":"CLANG_CXX_LANGUAGE_STANDARD=gnu++17"},{"type":"text","text":" for xcconfig files.)"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Building fails with ","type":"text"},{"type":"codeVoice","code":"'<Some Type Here>' is not a member type of enum '__ObjC.pxr'"},{"text":".","type":"text"},{"text":"\n","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"Solution"}]},{"text":": Add ","type":"text"},{"type":"codeVoice","code":"public typealias pxr = pxrInternal_v0_25_8__pxrReserved__"},{"text":" to one of your Swift files and rebuild.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"App launches but immediately crashes, and the console says something like ","type":"text"},{"code":"dyld[84216]: Library not loaded: @rpath\/Usd_UsdLux.framework\/Usd_UsdLux","type":"codeVoice"},{"text":"","type":"text"},{"text":"\n","type":"text"},{"inlineContent":[{"type":"text","text":"Solution"}],"type":"strong"},{"text":": In the Build Settings for your target, make sure that ","type":"text"},{"code":"Runpath Search Paths","type":"codeVoice"},{"text":" is set to ","type":"text"},{"code":"@executable_path\/Frameworks","type":"codeVoice"},{"text":". (","type":"text"},{"code":"LD_RUNPATH_SEARCH_PATHS=@executable_path\/Frameworks","type":"codeVoice"},{"text":" for xcconfig files.)","type":"text"},{"text":"\n","type":"text"},{"text":"Note: This should only affect command line executable targets.","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}],"kind":"content"}],"references":{"doc://SwiftUsd/documentation/SwiftUsd/DifferencesInSwift":{"role":"article","type":"topic","abstract":[{"type":"text","text":"Learn how the OpenUSD API is different in Swift"}],"url":"\/documentation\/swiftusd\/differencesinswift","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DifferencesInSwift","title":"Differences in Swift"},"doc://SwiftUsd/documentation/SwiftUsd/Capabilities":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Capabilities","kind":"article","url":"\/documentation\/swiftusd\/capabilities","role":"article","abstract":[{"type":"text","text":"Learn about the current capabilities of OpenUSD in Swift"}],"type":"topic","title":"Capabilities"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection"},"rdar://138337998":{"titleInlineContent":[{"text":"rdar:\/\/138337998: Command line app using Swift Package with binary targets can’t find dylibs at runtime","type":"text"}],"title":"rdar:\/\/138337998: Command line app using Swift Package with binary targets can’t find dylibs at runtime","url":"rdar:\/\/138337998","type":"link","identifier":"rdar:\/\/138337998"},"doc://SwiftUsd/documentation/SwiftUsd/CurrentLimitations":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CurrentLimitations","kind":"article","url":"\/documentation\/swiftusd\/currentlimitations","role":"article","abstract":[{"type":"text","text":"Learn about the current limitations of OpenUSD in Swift"}],"type":"topic","title":"Current Limitations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":[{"title":"Essentials","generated":true,"anchor":"Essentials","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Capabilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DifferencesInSwift","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CurrentLimitations"]}],"path":"\/seeAlsoSections","op":"replace"}]}]}