{"variants":[{"paths":["\/documentation\/swiftusd\/upgradechecklist"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftusd\/upgradechecklist"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Article","role":"article","title":"Upgrade Checklist","modules":[{"name":"OpenUSD"}]},"kind":"article","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Checklist for upgrading SwiftUsd to be based on a new OpenUSD version","type":"text"}],"seeAlsoSections":[{"title":"About this repo","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangeLog","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/OngoingWork","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ReleaseChecklist","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Miscellaneous"],"generated":true,"anchor":"About-this-repo"}],"sections":[],"identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UpgradeChecklist","interfaceLanguage":"swift"},"primaryContentSections":[{"content":[{"anchor":"1-Build-new-vanilla-OpenUSDs","type":"heading","level":2,"text":"1. Build new vanilla OpenUSDs"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Update source repo"}],"type":"paragraph"}]}]},{"code":["cd ~\/OpenUSD","git switch release","git pull"],"type":"codeListing","syntax":null},{"inlineContent":[{"type":"text","text":"Verify that "},{"type":"codeVoice","code":"git log"},{"type":"text","text":" shows the expected tag and the working tree is clean"}],"type":"paragraph"},{"type":"orderedList","start":2,"items":[{"content":[{"inlineContent":[{"type":"text","text":"Build OpenUSD with no extra flags to "},{"type":"codeVoice","code":"\/opt\/local\/OpenUSD"}],"type":"paragraph"}]}]},{"code":["rm -rf \/opt\/local\/OpenUSD","cd ~\/OpenUSD","python3 build_scripts\/build_usd.py \/opt\/local\/OpenUSD"],"type":"codeListing","syntax":null},{"inlineContent":[{"text":"This is mostly a smoke test to make sure your development can build vanilla OpenUSD properly. (E.g. if you have homebrew, vanilla OpenUSD might run into issues building if you don’t add ","type":"text"},{"type":"codeVoice","code":"--ignore-homebrew"},{"text":" as a build option.) I like to ","type":"text"},{"type":"codeVoice","code":"usdview"},{"text":" a model or two after the build finishes","type":"text"}],"type":"paragraph"},{"type":"orderedList","start":3,"items":[{"content":[{"inlineContent":[{"text":"Build OpenUSD with ","type":"text"},{"type":"codeVoice","code":"--no-python"},{"text":" to ","type":"text"},{"type":"codeVoice","code":"\/opt\/local\/OpenUSD_no-python"}],"type":"paragraph"}]}]},{"code":["rm -rf \/opt\/local\/OpenUSD_no-python","cd ~\/OpenUSD","python3 build_scripts\/build_usd.py --no-python \/opt\/local\/OpenUSD_no-python"],"type":"codeListing","syntax":null},{"inlineContent":[{"type":"text","text":"This build will be used by "},{"code":"ast-answerer","type":"codeVoice"},{"type":"text","text":" later"}],"type":"paragraph"},{"anchor":"2-Upgrade-SwiftUsdopenusd-source","type":"heading","level":2,"text":"2. Upgrade SwiftUsd\/openusd-source"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Undo the old patch"}],"type":"paragraph"}]}],"type":"orderedList"},{"syntax":null,"code":["cd ~\/SwiftUsd\/openusd-source","git restore .","git clean -fd","git status"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"Make sure the working tree is clean"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Update the source repo"}]}]}],"start":2,"type":"orderedList"},{"syntax":null,"code":["git switch release","git pull"],"type":"codeListing"},{"inlineContent":[{"text":"Verify that ","type":"text"},{"code":"git log","type":"codeVoice"},{"text":" shows the expected tag and the working tree is clean","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Apply the hunks from "},{"type":"codeVoice","code":"~\/SwiftUsd\/openusd-patch.patch"},{"type":"text","text":" to "},{"type":"codeVoice","code":"~\/SwiftUsd\/openusd-source"},{"type":"text","text":""},{"type":"text","text":"\n"},{"type":"text","text":"The size of the patch has shrunk a lot from what it used to be, so I prefer to manually apply the hunks by hand instead of using "},{"type":"codeVoice","code":"patch"},{"type":"text","text":". Sometimes hunks get moved around or are no longer needed, and I want to have at least briefly looked at any changes that are near any of the hunks in the patch, in case there are changes in the new version of OpenUSD that impact any of the hunks."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet#Generating-a-new-patch","overridingTitle":"Generate a new openusd-patch.patch","isActive":true,"type":"reference","overridingTitleInlineContent":[{"type":"text","text":"Generate a new openusd-patch.patch"}]},{"text":" and check in into the repo as ","type":"text"},{"code":"~\/SwiftUsd\/openusd-patch.patch","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"overridingTitleInlineContent":[{"text":"Rebuild the OpenUSD dylibs in SwiftUsd","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/BuildingLocally","type":"reference","overridingTitle":"Rebuild the OpenUSD dylibs in SwiftUsd","isActive":true},{"type":"text","text":". Remember to remove "},{"code":"~\/SwiftUsd\/openusd-builds\/*","type":"codeVoice"},{"type":"text","text":" first."}]}]}],"start":3,"type":"orderedList"},{"level":2,"anchor":"3-Run-ast-answerer-on-the-new-optlocalOpenUSDno-python","text":"3. Run ast-answerer on the new \/opt\/local\/OpenUSD_no-python","type":"heading"},{"inlineContent":[{"text":"Make sure to remove the ","type":"text"},{"code":"build\/AstAnswererOutputs","type":"codeVoice"},{"text":" file to run the analysis from scratch. You may need to make small modifications to ","type":"text"},{"code":"ast-answerer","type":"codeVoice"},{"text":" and re-run it multiple times, because it’s designed to be very sensitive to any changes in OpenUSD. (For example, if OpenUSD removes some source files or types, that will often cause ","type":"text"},{"code":"ast-answerer","type":"codeVoice"},{"text":"‘s internal tests to fail. ast-answerer is intentionally brittle in this fashion, because it’s worth taking the time to double check that those files\/types really were removed, instead of ast-answerer somehow now missing files\/types in a new OpenUSD that are still present.)","type":"text"}],"type":"paragraph"},{"level":2,"anchor":"4-Normal-upgraderelease-process-for-SwiftUsd","text":"4. Normal upgrade\/release process for SwiftUsd","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Follow the ","type":"text"},{"isActive":true,"overridingTitleInlineContent":[{"text":"Release Checklist","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ReleaseChecklist","overridingTitle":"Release Checklist","type":"reference"},{"text":", this is just an abridged overview of the process. Also, if there are new compiler errors\/bugs that arise from the new OpenUSD version, you’ll have to fix them, and may need to redo prior steps multiple times, such as modifying the patch and rebuilding OpenUSD dylibs for SwiftUsd.","type":"text"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Move the code generated by "},{"type":"codeVoice","code":"ast-answerer"},{"type":"text","text":" to "},{"type":"codeVoice","code":"~\/SwiftUsd\/generated\/*"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Remove ","type":"text"},{"type":"codeVoice","code":"~\/SwiftUsd\/swift-package"},{"text":", then run ","type":"text"},{"type":"codeVoice","code":"~\/SwiftUsd\/scripts\/make-swift-package"},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Upgrade the Pixar namespace in "},{"code":"~\/SwiftUsd\/source\/OpenUSD.swift","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Test SwiftUsd. Aside from using ","type":"text"},{"identifier":"https:\/\/github.com\/apple\/SwiftUsd-Tests","type":"reference","isActive":true},{"text":", opt for full testing of all processes, including iOS apps and running the test suite on multiple Macs. Updating to a new OpenUSD version is a significant change.","type":"text"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"If there are test failures in the test suite, investigate them until you 100% understand them. The test suite has caught serious regressions in two published releases of OpenUSD to date, so test failures are likely either indicative of correct changes in OpenUSD’s behavior, or new regressions.","type":"text"}]}],"type":"aside","style":"important","name":"Important"},{"type":"orderedList","start":5,"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Update documentation, then release SwiftUsd","type":"text"}]}]}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"references":{"doc://SwiftUsd/documentation/SwiftUsd/OngoingWork":{"role":"article","url":"\/documentation\/swiftusd\/ongoingwork","type":"topic","kind":"article","title":"Ongoing Work","abstract":[{"type":"text","text":"In-progress and future tasks for improving OpenUSD in Swift"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/OngoingWork"},"doc://SwiftUsd/documentation/SwiftUsd/BuildingLocally":{"url":"\/documentation\/swiftusd\/buildinglocally","role":"article","title":"Building locally","type":"topic","abstract":[{"text":"Learn how to use SwiftUsd with local\/existing OpenUSD binaries","type":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/BuildingLocally","kind":"article"},"doc://SwiftUsd/documentation/SwiftUsd/Miscellaneous":{"role":"article","url":"\/documentation\/swiftusd\/miscellaneous","type":"topic","kind":"article","title":"Miscellaneous","abstract":[{"type":"text","text":"Miscellaneous details about this repo"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Miscellaneous"},"doc://SwiftUsd/documentation/SwiftUsd/ChangeLog":{"role":"article","type":"topic","abstract":[{"type":"text","text":"Changes to SwiftUsd"}],"url":"\/documentation\/swiftusd\/changelog","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangeLog","title":"Change Log"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection"},"doc://SwiftUsd/documentation/SwiftUsd/ReleaseChecklist":{"role":"article","url":"\/documentation\/swiftusd\/releasechecklist","type":"topic","kind":"article","title":"Release Checklist","abstract":[{"type":"text","text":"Checklist for releasing new versions of SwiftUsd"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ReleaseChecklist"},"doc://SwiftUsd/documentation/SwiftUsd/CheatSheet":{"role":"article","url":"\/documentation\/swiftusd\/cheatsheet","type":"topic","kind":"article","title":"Cheat sheet","abstract":[{"type":"text","text":"Tips for advanced users modifying this repo"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet"},"https://github.com/apple/SwiftUsd-Tests":{"identifier":"https:\/\/github.com\/apple\/SwiftUsd-Tests","title":"SwiftUsd-Tests","url":"https:\/\/github.com\/apple\/SwiftUsd-Tests","titleInlineContent":[{"type":"text","text":"SwiftUsd-Tests"}],"type":"link"},"doc://SwiftUsd/documentation/SwiftUsd/CheatSheet#Generating-a-new-patch":{"kind":"section","abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet#Generating-a-new-patch","title":"Generating a new patch","url":"\/documentation\/swiftusd\/cheatsheet#Generating-a-new-patch","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ChangeLog","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/OngoingWork","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheatSheet","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ReleaseChecklist","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/Miscellaneous"],"generated":true,"anchor":"About-this-repo","title":"About this repo"}],"op":"replace","path":"\/seeAlsoSections"}]}]}