{"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"sections":[],"abstract":[{"type":"text","text":"Learn how to use the "},{"type":"codeVoice","code":"pxr::Work"},{"type":"text","text":" library for multithreading in Swift"}],"metadata":{"modules":[{"name":"OpenUSD"}],"title":"Using libWork","role":"article","roleHeading":"Article"},"kind":"article","identifier":{"url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingLibWork","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftusd\/usinglibwork"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/swiftusd\/usinglibwork"]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion"],"title":"New symbol documentation","anchor":"New-symbol-documentation"}],"primaryContentSections":[{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"Overview"},{"type":"paragraph","inlineContent":[{"text":"OpenUSD provides the ","type":"text"},{"isActive":true,"identifier":"https:\/\/openusd.org\/release\/api\/work_page_front.html","type":"reference"},{"text":" library to simplify C++ multithreading. A select portion of this API is available in Swift.","type":"text"}]},{"type":"aside","name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"Work","type":"codeVoice"},{"text":" is backed by a different multithreading implementation than Swift Concurrency. In some cases, Swift Concurrency may be a better fit for a problem than using ","type":"text"},{"code":"libWork","type":"codeVoice"},{"text":" from Swift.","type":"text"}]}]},{"level":2,"text":"Detached tasks","anchor":"Detached-tasks","type":"heading"},{"inlineContent":[{"type":"text","text":"Use "},{"type":"reference","overridingTitleInlineContent":[{"type":"codeVoice","code":"pxr.WorkRunDetachedTask(_:)"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/WorkRunDetachedTask(_:)","isActive":true,"overridingTitle":"pxr.WorkRunDetachedTask(_:)"},{"type":"text","text":" to invoke a closure asynchronously."}],"type":"paragraph"},{"level":2,"text":"Loops","anchor":"Loops","type":"heading"},{"inlineContent":[{"text":"Use ","type":"text"},{"isActive":true,"overridingTitle":"pxr.WorkSerialForN(_:_:)","type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/WorkSerialForN(_:_:)","overridingTitleInlineContent":[{"type":"codeVoice","code":"pxr.WorkSerialForN(_:_:)"}]},{"text":" to easily temporarily turn off multithreading of a parallel loop for easier debugging.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Use ","type":"text"},{"isActive":true,"overridingTitle":"pxr.WorkParallelForN(_:_:)","overridingTitleInlineContent":[{"type":"codeVoice","code":"pxr.WorkParallelForN(_:_:)"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/WorkParallelForN(_:_:)","type":"reference"},{"text":" to run a closure in parallel over a range.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Use ","type":"text"},{"overridingTitleInlineContent":[{"type":"codeVoice","code":"pxr.WorkParallelForEach(_:_:)"}],"type":"reference","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/WorkParallelForEach(_:_:)","isActive":true,"overridingTitle":"pxr.WorkParallelForEach(_:_:)"},{"text":" to run a closure in parallel over a collection.","type":"text"}],"type":"paragraph"},{"level":2,"text":"Reduce","anchor":"Reduce","type":"heading"},{"inlineContent":[{"text":"Use ","type":"text"},{"isActive":true,"type":"reference","overridingTitleInlineContent":[{"type":"codeVoice","code":"pxr.WorkParallelReduceN(_:_:_:_:)"}],"overridingTitle":"pxr.WorkParallelReduceN(_:_:_:_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/WorkParallelReduceN(_:_:_:_:)"},{"text":" to map and reduce a range in parallel.","type":"text"}],"type":"paragraph"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/WorkParallelForN(_:_:)":{"title":"WorkParallelForN(_:_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/WorkParallelForN(_:_:)","type":"topic","url":"\/documentation\/openusd\/c++\/pxr\/workparallelforn(_:_:)","kind":"symbol","role":"symbol","abstract":[{"text":"Runs ","type":"text"},{"code":"closure","type":"codeVoice"},{"text":" in parallel over the range 0 to n.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WorkParallelForN","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"begin","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"end","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ())","kind":"text"}]},"doc://SwiftUsd/documentation/SwiftUsd/UsingEditContexts":{"role":"collectionGroup","type":"topic","url":"\/documentation\/swiftusd\/usingeditcontexts","abstract":[{"type":"text","text":"Using "},{"type":"codeVoice","code":"pxr.UsdEditContext"},{"type":"text","text":" in Swift"}],"title":"Using edit contexts","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts"},"doc://SwiftUsd/documentation/SwiftUsd/CheckingForValidity":{"title":"Checking for validity","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","type":"topic","url":"\/documentation\/swiftusd\/checkingforvalidity","kind":"article","role":"article","abstract":[{"text":"Checking for ","type":"text"},{"code":"IsValid()","type":"codeVoice"},{"text":" and null pointers in Swift","type":"text"}]},"doc://SwiftUsd/documentation/SwiftUsd/CreatingPointers":{"type":"topic","abstract":[{"text":"Creating ","type":"text"},{"type":"codeVoice","code":"pxr.TfRefPtr"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"pxr.TfWeakPtr"},{"text":" in Swift","type":"text"}],"role":"collectionGroup","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","url":"\/documentation\/swiftusd\/creatingpointers","title":"Creating pointers"},"doc://SwiftUsd/documentation/SwiftUsd/DereferencingPointers":{"type":"topic","url":"\/documentation\/swiftusd\/dereferencingpointers","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","abstract":[{"type":"text","text":"Safely dereferencing "},{"code":"pxr.TfRefPtr","type":"codeVoice"},{"type":"text","text":" and "},{"code":"pxr.TfWeakPtr","type":"codeVoice"},{"type":"text","text":" in Swift"}],"kind":"article","role":"collectionGroup","title":"Dereferencing pointers"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection"},"https://openusd.org/release/api/work_page_front.html":{"url":"https:\/\/openusd.org\/release\/api\/work_page_front.html","identifier":"https:\/\/openusd.org\/release\/api\/work_page_front.html","type":"link","titleInlineContent":[{"text":"Work","type":"text"}],"title":"Work"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfDiagnosticFacilities":{"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","title":"Working with Tf Diagnostic Facilities","role":"collectionGroup","abstract":[{"type":"text","text":"Learn how to use the Tf diagnostic facilities in Swift"}],"url":"\/documentation\/swiftusd\/workingwithtfdiagnosticfacilities","type":"topic","kind":"article"},"doc://SwiftUsd/documentation/SwiftUsd/ConvenientExtensions":{"title":"Convenient extensions","abstract":[{"type":"text","text":"Extensions that make OpenUSD nicer to use in Swift"}],"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","url":"\/documentation\/swiftusd\/convenientextensions"},"doc://SwiftUsd/documentation/SwiftUsd/TypeConversion":{"kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion","url":"\/documentation\/swiftusd\/typeconversion","abstract":[],"role":"collectionGroup","title":"Type conversion","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/WorkSerialForN(_:_:)":{"abstract":[{"text":"A serial version of WorkParallelForN as a drop in replacement to","type":"text"},{"text":" ","type":"text"},{"text":"selectively turn off multithreading for a single parallel loop for easier","type":"text"},{"text":" ","type":"text"},{"text":"debugging.","type":"text"}],"kind":"symbol","role":"symbol","title":"WorkSerialForN(_:_:)","url":"\/documentation\/openusd\/c++\/pxr\/workserialforn(_:_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WorkSerialForN","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"begin","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"end","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ())","kind":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/WorkSerialForN(_:_:)"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/WorkRunDetachedTask(_:)":{"abstract":[{"text":"Invoke ","type":"text"},{"code":"closure","type":"codeVoice"},{"text":" asynchronously, discard any errors it produces, and provide","type":"text"},{"text":" ","type":"text"},{"text":"no way to wait for it to complete.","type":"text"}],"kind":"symbol","role":"symbol","title":"WorkRunDetachedTask(_:)","url":"\/documentation\/openusd\/c++\/pxr\/workrundetachedtask(_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WorkRunDetachedTask","kind":"identifier"},{"text":"(() -> ())","kind":"text"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/WorkRunDetachedTask(_:)"},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/WorkParallelReduceN(_:_:_:_:)":{"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/WorkParallelReduceN(_:_:_:_:)","abstract":[{"text":"Recursively splits the range [0, ","type":"text"},{"type":"codeVoice","code":"n"},{"text":") into subranges, which are then","type":"text"},{"text":" ","type":"text"},{"text":"reduced by invoking ","type":"text"},{"type":"codeVoice","code":"loopCallback"},{"text":" in parallel.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/openusd\/c++\/pxr\/workparallelreducen(_:_:_:_:)","title":"WorkParallelReduceN(_:_:_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WorkParallelReduceN","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O7OpenUSDE19WorkParallelReduceNyxx_SixSi_SixtYbXExx_xtYbXEtlFZ1TL_xmfp"},{"text":", ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", (","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O7OpenUSDE19WorkParallelReduceNyxx_SixSi_SixtYbXExx_xtYbXEtlFZ1TL_xmfp"},{"text":") -> ","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O7OpenUSDE19WorkParallelReduceNyxx_SixSi_SixtYbXExx_xtYbXEtlFZ1TL_xmfp"},{"text":", (","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O7OpenUSDE19WorkParallelReduceNyxx_SixSi_SixtYbXExx_xtYbXEtlFZ1TL_xmfp"},{"text":", ","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O7OpenUSDE19WorkParallelReduceNyxx_SixSi_SixtYbXExx_xtYbXEtlFZ1TL_xmfp"},{"text":") -> ","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O7OpenUSDE19WorkParallelReduceNyxx_SixSi_SixtYbXExx_xtYbXEtlFZ1TL_xmfp"},{"text":") -> ","kind":"text"},{"text":"T","kind":"typeIdentifier","preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O7OpenUSDE19WorkParallelReduceNyxx_SixSi_SixtYbXExx_xtYbXEtlFZ1TL_xmfp"}]},"doc://SwiftUsd/documentation/OpenUSD/C++/pxr/WorkParallelForEach(_:_:)":{"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/C++\/pxr\/WorkParallelForEach(_:_:)","url":"\/documentation\/openusd\/c++\/pxr\/workparallelforeach(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"WorkParallelForEach"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"C"},{"kind":"text","text":">("},{"preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O7OpenUSDE19WorkParallelForEachyyx_y7ElementQzYbXEtSlRzlFZ1CL_xmfp","kind":"typeIdentifier","text":"C"},{"kind":"text","text":", ("},{"preciseIdentifier":"s:So021pxrInternal_v0_25_8__A10Reserved__O7OpenUSDE19WorkParallelForEachyyx_y7ElementQzYbXEtSlRzlFZ1CL_xmfp","kind":"typeIdentifier","text":"C"},{"kind":"text","text":"."},{"preciseIdentifier":"s:ST7ElementQa","kind":"typeIdentifier","text":"Element"},{"kind":"text","text":") -> ())"}],"title":"WorkParallelForEach(_:_:)","role":"symbol","abstract":[{"type":"text","text":"Runs "},{"type":"codeVoice","code":"closure"},{"type":"text","text":" in parallel over the elements in "},{"type":"codeVoice","code":"collection"}],"type":"topic"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfNotice":{"title":"Working with TfNotice","url":"\/documentation\/swiftusd\/workingwithtfnotice","type":"topic","role":"article","kind":"article","abstract":[{"type":"text","text":"Learn how to use the TfNotice notification subsystem in Swift"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfErrorMark":{"kind":"article","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","abstract":[{"text":"Learn how to use TfErrorMark in Swift","type":"text"}],"role":"article","url":"\/documentation\/swiftusd\/workingwithtferrormark","title":"Working with TfErrorMark"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"generated":true,"title":"New symbol documentation","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion"],"anchor":"New-symbol-documentation"}],"path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}