{"metadata":{"modules":[{"name":"OpenUSD"}],"roleHeading":"API Collection","title":"Working with Tf Diagnostic Facilities","role":"collectionGroup"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD"]]},"sections":[],"topicSections":[{"anchor":"Tf-diagnostic-functions","title":"Tf diagnostic functions","identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_CODING_ERROR(_:_:_:_:_:)","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_CODING_WARNING(_:_:_:_:_:)","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_DIAGNOSTIC_FATAL_ERROR(_:_:_:_:_:)","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_DIAGNOSTIC_NONFATAL_ERROR(_:_:_:_:_:)","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_DIAGNOSTIC_WARNING(_:_:_:_:_:)","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_ERROR(_:_:_:_:_:_:)-9qyc","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_ERROR(_:_:_:_:_:_:)-396h1","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_ERROR(_:_:_:_:_:_:_:)","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_FATAL_CODING_ERROR(_:_:_:_:_:)","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_FATAL_ERROR(_:_:_:_:_:)","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_QUIET_ERROR(_:_:_:_:_:_:)","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_QUIET_ERROR(_:_:_:_:_:_:_:)","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_RUNTIME_ERROR(_:_:_:_:_:)","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_STATUS(_:_:_:_:_:)","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_STATUS(_:_:_:_:_:_:)","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_STATUS(_:_:_:_:_:_:_:)","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_WARN(_:_:_:_:_:)","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_WARN(_:_:_:_:_:_:)-2rlak","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_WARN(_:_:_:_:_:_:)-7rl7j","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_WARN(_:_:_:_:_:_:_:)"]},{"anchor":"Tf-diagnostic-macros","title":"Tf diagnostic macros","abstract":[{"text":"Note: In Swift, ","type":"text"},{"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_DEV_AXIOM(_:)","isActive":true,"type":"reference"},{"text":" only runs when the Swift source code that uses it was compiled with the ","type":"text"},{"code":"-DDEBUG","type":"codeVoice"},{"text":" flag (i.e. compiled in Debug and not in Release). This differs from the behavior in C++, where ","type":"text"},{"code":"TF_DEV_AXIOM","type":"codeVoice"},{"text":" only runs when the OpenUSD binary was compiled in Debug mode.","type":"text"}],"identifiers":["doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_AXIOM(_:)","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_DEV_AXIOM(_:)","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_VERIFY(_:_:)"]}],"seeAlsoSections":[{"generated":true,"anchor":"New-symbol-documentation","title":"New symbol documentation","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingLibWork","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion"]}],"abstract":[{"type":"text","text":"Learn how to use the Tf diagnostic facilities in Swift"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"text":"Overview","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"OpenUSD includes several C++ macros for issuing coding errors, runtime errors, warnings and status messages. SwiftUsd exposes this system to Swift via Swift functions and Swift macros."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"https:\/\/openusd.org\/release\/api\/page_tf__diagnostic.html"},{"type":"text","text":" for more information."}]}]}],"variants":[{"paths":["\/documentation\/swiftusd\/workingwithtfdiagnosticfacilities"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftusd\/workingwithtfdiagnosticfacilities"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfDiagnosticFacilities"},"kind":"article","references":{"doc://SwiftUsd/documentation/OpenUSD/TF_ERROR(_:_:_:_:_:_:_:)":{"url":"\/documentation\/openusd\/tf_error(_:_:_:_:_:_:_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TF_ERROR","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfDiagnosticInfo","kind":"typeIdentifier","preciseIdentifier":"c:diagnosticHelper.h@N@pxr@T@TfDiagnosticInfo"},{"text":", ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfEnum","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfEnum"},{"text":", ","kind":"text"},{"text":"std","kind":"typeIdentifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"string","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@string"},{"text":", ","kind":"text"},{"text":"StaticString","kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV"},{"text":", ","kind":"text"},{"text":"StaticString","kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV"},{"text":", ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"StaticString","kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_ERROR(_:_:_:_:_:_:_:)","title":"TF_ERROR(_:_:_:_:_:_:_:)","abstract":[]},"doc://SwiftUsd/documentation/SwiftUsd/ConvenientExtensions":{"title":"Convenient extensions","abstract":[{"type":"text","text":"Extensions that make OpenUSD nicer to use in Swift"}],"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","url":"\/documentation\/swiftusd\/convenientextensions"},"doc://SwiftUsd/documentation/OpenUSD/TF_CODING_ERROR(_:_:_:_:_:)":{"url":"\/documentation\/openusd\/tf_coding_error(_:_:_:_:_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TF_CODING_ERROR","kind":"identifier"},{"text":"(","kind":"text"},{"text":"std","kind":"typeIdentifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"string","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@string"},{"text":", ","kind":"text"},{"text":"StaticString","kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV"},{"text":", ","kind":"text"},{"text":"StaticString","kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV"},{"text":", ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"StaticString","kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_CODING_ERROR(_:_:_:_:_:)","title":"TF_CODING_ERROR(_:_:_:_:_:)","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/TF_DIAGNOSTIC_WARNING(_:_:_:_:_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TF_DIAGNOSTIC_WARNING","kind":"identifier"},{"text":"(","kind":"text"},{"text":"std","kind":"typeIdentifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"string","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@string"},{"text":", ","kind":"text"},{"text":"StaticString","kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV"},{"text":", ","kind":"text"},{"text":"StaticString","kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV"},{"text":", ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"StaticString","kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_DIAGNOSTIC_WARNING(_:_:_:_:_:)","kind":"symbol","type":"topic","title":"TF_DIAGNOSTIC_WARNING(_:_:_:_:_:)","url":"\/documentation\/openusd\/tf_diagnostic_warning(_:_:_:_:_:)","role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/TF_QUIET_ERROR(_:_:_:_:_:_:_:)":{"url":"\/documentation\/openusd\/tf_quiet_error(_:_:_:_:_:_:_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TF_QUIET_ERROR","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfEnum","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfEnum"},{"text":", ","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfDiagnosticInfo","kind":"typeIdentifier","preciseIdentifier":"c:diagnosticHelper.h@N@pxr@T@TfDiagnosticInfo"},{"text":", ","kind":"text"},{"text":"std","kind":"typeIdentifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"string","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@string"},{"text":", ","kind":"text"},{"text":"StaticString","kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV"},{"text":", ","kind":"text"},{"text":"StaticString","kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV"},{"text":", ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"StaticString","kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_QUIET_ERROR(_:_:_:_:_:_:_:)","title":"TF_QUIET_ERROR(_:_:_:_:_:_:_:)","abstract":[]},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfErrorMark":{"kind":"article","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","abstract":[{"text":"Learn how to use TfErrorMark in Swift","type":"text"}],"role":"article","url":"\/documentation\/swiftusd\/workingwithtferrormark","title":"Working with TfErrorMark"},"doc://SwiftUsd/documentation/SwiftUsd/UsingLibWork":{"type":"topic","title":"Using libWork","url":"\/documentation\/swiftusd\/usinglibwork","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingLibWork","kind":"article","abstract":[{"type":"text","text":"Learn how to use the "},{"type":"codeVoice","code":"pxr::Work"},{"type":"text","text":" library for multithreading in Swift"}],"role":"article"},"doc://SwiftUsd/documentation/SwiftUsd/WorkingWithTfNotice":{"title":"Working with TfNotice","url":"\/documentation\/swiftusd\/workingwithtfnotice","type":"topic","role":"article","kind":"article","abstract":[{"type":"text","text":"Learn how to use the TfNotice notification subsystem in Swift"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice"},"doc://SwiftUsd/documentation/OpenUSD/TF_VERIFY(_:_:)":{"url":"\/documentation\/openusd\/tf_verify(_:_:)","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"macro","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TF_VERIFY","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","title":"TF_VERIFY(_:_:)","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_VERIFY(_:_:)"},"doc://SwiftUsd/documentation/OpenUSD/TF_ERROR(_:_:_:_:_:_:)-396h1":{"url":"\/documentation\/openusd\/tf_error(_:_:_:_:_:_:)-396h1","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"TF_ERROR"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@E@TfDiagnosticType","text":"TfDiagnosticType"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std","text":"std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@string","text":"string"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_ERROR(_:_:_:_:_:_:)-396h1","title":"TF_ERROR(_:_:_:_:_:_:)","abstract":[]},"doc://SwiftUsd/documentation/SwiftUsd/CreatingPointers":{"type":"topic","abstract":[{"text":"Creating ","type":"text"},{"type":"codeVoice","code":"pxr.TfRefPtr"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"pxr.TfWeakPtr"},{"text":" in Swift","type":"text"}],"role":"collectionGroup","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","url":"\/documentation\/swiftusd\/creatingpointers","title":"Creating pointers"},"doc://SwiftUsd/documentation/SwiftUsd/DereferencingPointers":{"type":"topic","url":"\/documentation\/swiftusd\/dereferencingpointers","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","abstract":[{"type":"text","text":"Safely dereferencing "},{"code":"pxr.TfRefPtr","type":"codeVoice"},{"type":"text","text":" and "},{"code":"pxr.TfWeakPtr","type":"codeVoice"},{"type":"text","text":" in Swift"}],"kind":"article","role":"collectionGroup","title":"Dereferencing pointers"},"doc://SwiftUsd/documentation/OpenUSD/TF_CODING_WARNING(_:_:_:_:_:)":{"url":"\/documentation\/openusd\/tf_coding_warning(_:_:_:_:_:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"TF_CODING_WARNING"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std","text":"std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@string","text":"string"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_CODING_WARNING(_:_:_:_:_:)","title":"TF_CODING_WARNING(_:_:_:_:_:)","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/TF_AXIOM(_:)":{"title":"TF_AXIOM(_:)","role":"symbol","fragments":[{"text":"macro","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TF_AXIOM","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/openusd\/tf_axiom(_:)","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_AXIOM(_:)"},"doc://SwiftUsd/documentation/OpenUSD/TF_DIAGNOSTIC_NONFATAL_ERROR(_:_:_:_:_:)":{"url":"\/documentation\/openusd\/tf_diagnostic_nonfatal_error(_:_:_:_:_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TF_DIAGNOSTIC_NONFATAL_ERROR","kind":"identifier"},{"text":"(","kind":"text"},{"text":"std","kind":"typeIdentifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"string","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@string"},{"text":", ","kind":"text"},{"text":"StaticString","kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV"},{"text":", ","kind":"text"},{"text":"StaticString","kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV"},{"text":", ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"StaticString","kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_DIAGNOSTIC_NONFATAL_ERROR(_:_:_:_:_:)","title":"TF_DIAGNOSTIC_NONFATAL_ERROR(_:_:_:_:_:)","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/TF_FATAL_ERROR(_:_:_:_:_:)":{"url":"\/documentation\/openusd\/tf_fatal_error(_:_:_:_:_:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"TF_FATAL_ERROR"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std","text":"std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@string","text":"string"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO","text":"Never"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_FATAL_ERROR(_:_:_:_:_:)","title":"TF_FATAL_ERROR(_:_:_:_:_:)","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/TF_FATAL_CODING_ERROR(_:_:_:_:_:)":{"url":"\/documentation\/openusd\/tf_fatal_coding_error(_:_:_:_:_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TF_FATAL_CODING_ERROR","kind":"identifier"},{"text":"(","kind":"text"},{"text":"std","kind":"typeIdentifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"string","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@string"},{"text":", ","kind":"text"},{"text":"StaticString","kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV"},{"text":", ","kind":"text"},{"text":"StaticString","kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV"},{"text":", ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"StaticString","kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV"},{"text":") -> ","kind":"text"},{"text":"Never","kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_FATAL_CODING_ERROR(_:_:_:_:_:)","title":"TF_FATAL_CODING_ERROR(_:_:_:_:_:)","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/TF_WARN(_:_:_:_:_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"TF_WARN"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"string","preciseIdentifier":"c:@N@std@N@__1@string"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"StaticString","preciseIdentifier":"s:s12StaticStringV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"StaticString","preciseIdentifier":"s:s12StaticStringV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"StaticString","preciseIdentifier":"s:s12StaticStringV"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_WARN(_:_:_:_:_:)","type":"topic","title":"TF_WARN(_:_:_:_:_:)","abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/tf_warn(_:_:_:_:_:)"},"doc://SwiftUsd/documentation/OpenUSD/TF_WARN(_:_:_:_:_:_:)-2rlak":{"title":"TF_WARN(_:_:_:_:_:_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TF_WARN","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@pxr@S@TfEnum","text":"TfEnum","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@N@std","text":"std","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@N@std@N@__1@string","text":"string","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s12StaticStringV","text":"StaticString","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s12StaticStringV","text":"StaticString","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s12StaticStringV","text":"StaticString","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/openusd\/tf_warn(_:_:_:_:_:_:)-2rlak","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_WARN(_:_:_:_:_:_:)-2rlak"},"doc://SwiftUsd/documentation/OpenUSD/TF_STATUS(_:_:_:_:_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"TF_STATUS"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"string","preciseIdentifier":"c:@N@std@N@__1@string"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"StaticString","preciseIdentifier":"s:s12StaticStringV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"StaticString","preciseIdentifier":"s:s12StaticStringV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"StaticString","preciseIdentifier":"s:s12StaticStringV"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_STATUS(_:_:_:_:_:)","type":"topic","title":"TF_STATUS(_:_:_:_:_:)","abstract":[],"kind":"symbol","url":"\/documentation\/openusd\/tf_status(_:_:_:_:_:)"},"doc://SwiftUsd/documentation/SwiftUsd/CheckingForValidity":{"title":"Checking for validity","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","type":"topic","url":"\/documentation\/swiftusd\/checkingforvalidity","kind":"article","role":"article","abstract":[{"text":"Checking for ","type":"text"},{"code":"IsValid()","type":"codeVoice"},{"text":" and null pointers in Swift","type":"text"}]},"doc://SwiftUsd/documentation/OpenUSD/TF_DEV_AXIOM(_:)":{"title":"TF_DEV_AXIOM(_:)","role":"symbol","fragments":[{"text":"macro","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TF_DEV_AXIOM","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/openusd\/tf_dev_axiom(_:)","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_DEV_AXIOM(_:)"},"doc://SwiftUsd/documentation/OpenUSD/TF_RUNTIME_ERROR(_:_:_:_:_:)":{"url":"\/documentation\/openusd\/tf_runtime_error(_:_:_:_:_:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"TF_RUNTIME_ERROR"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std","text":"std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@string","text":"string"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_RUNTIME_ERROR(_:_:_:_:_:)","title":"TF_RUNTIME_ERROR(_:_:_:_:_:)","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/TF_DIAGNOSTIC_FATAL_ERROR(_:_:_:_:_:)":{"url":"\/documentation\/openusd\/tf_diagnostic_fatal_error(_:_:_:_:_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TF_DIAGNOSTIC_FATAL_ERROR","kind":"identifier"},{"text":"(","kind":"text"},{"text":"std","kind":"typeIdentifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"string","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@string"},{"text":", ","kind":"text"},{"text":"StaticString","kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV"},{"text":", ","kind":"text"},{"text":"StaticString","kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV"},{"text":", ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"StaticString","kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV"},{"text":") -> ","kind":"text"},{"text":"Never","kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_DIAGNOSTIC_FATAL_ERROR(_:_:_:_:_:)","title":"TF_DIAGNOSTIC_FATAL_ERROR(_:_:_:_:_:)","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/TF_STATUS(_:_:_:_:_:_:_:)":{"role":"symbol","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"TF_STATUS"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:diagnosticHelper.h@N@pxr@T@TfDiagnosticInfo","text":"TfDiagnosticInfo"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfEnum","text":"TfEnum"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std","text":"std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@string","text":"string"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":")"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_STATUS(_:_:_:_:_:_:_:)","type":"topic","title":"TF_STATUS(_:_:_:_:_:_:_:)","url":"\/documentation\/openusd\/tf_status(_:_:_:_:_:_:_:)"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection"},"doc://SwiftUsd/documentation/OpenUSD/TF_WARN(_:_:_:_:_:_:_:)":{"kind":"symbol","role":"symbol","url":"\/documentation\/openusd\/tf_warn(_:_:_:_:_:_:_:)","abstract":[],"type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_WARN(_:_:_:_:_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"TF_WARN"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:diagnosticHelper.h@N@pxr@T@TfDiagnosticInfo","text":"TfDiagnosticInfo"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfEnum","text":"TfEnum"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std","text":"std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@string","text":"string"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":")"}],"title":"TF_WARN(_:_:_:_:_:_:_:)"},"doc://SwiftUsd/documentation/OpenUSD/TF_ERROR(_:_:_:_:_:_:)-9qyc":{"url":"\/documentation\/openusd\/tf_error(_:_:_:_:_:_:)-9qyc","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"TF_ERROR"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfEnum","text":"TfEnum"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std","text":"std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@string","text":"string"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_ERROR(_:_:_:_:_:_:)-9qyc","title":"TF_ERROR(_:_:_:_:_:_:)","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/TF_STATUS(_:_:_:_:_:_:)":{"url":"\/documentation\/openusd\/tf_status(_:_:_:_:_:_:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"TF_STATUS"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfEnum","text":"TfEnum"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std","text":"std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@string","text":"string"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_STATUS(_:_:_:_:_:_:)","title":"TF_STATUS(_:_:_:_:_:_:)","abstract":[]},"doc://SwiftUsd/documentation/SwiftUsd/UsingEditContexts":{"role":"collectionGroup","type":"topic","url":"\/documentation\/swiftusd\/usingeditcontexts","abstract":[{"type":"text","text":"Using "},{"type":"codeVoice","code":"pxr.UsdEditContext"},{"type":"text","text":" in Swift"}],"title":"Using edit contexts","kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts"},"doc://SwiftUsd/documentation/SwiftUsd/TypeConversion":{"kind":"article","identifier":"doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion","url":"\/documentation\/swiftusd\/typeconversion","abstract":[],"role":"collectionGroup","title":"Type conversion","type":"topic"},"doc://SwiftUsd/documentation/OpenUSD/TF_QUIET_ERROR(_:_:_:_:_:_:)":{"url":"\/documentation\/openusd\/tf_quiet_error(_:_:_:_:_:_:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"TF_QUIET_ERROR"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra","text":"pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@TfEnum","text":"TfEnum"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std","text":"std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@string","text":"string"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_QUIET_ERROR(_:_:_:_:_:_:)","title":"TF_QUIET_ERROR(_:_:_:_:_:_:)","abstract":[]},"doc://SwiftUsd/documentation/OpenUSD/TF_WARN(_:_:_:_:_:_:)-7rl7j":{"role":"symbol","url":"\/documentation\/openusd\/tf_warn(_:_:_:_:_:_:)-7rl7j","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/TF_WARN(_:_:_:_:_:_:)-7rl7j","type":"topic","abstract":[],"title":"TF_WARN(_:_:_:_:_:_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TF_WARN","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pxr","kind":"typeIdentifier","preciseIdentifier":"s:7OpenUSD3pxra"},{"text":".","kind":"text"},{"text":"TfDiagnosticType","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@E@TfDiagnosticType"},{"text":", ","kind":"text"},{"text":"std","kind":"typeIdentifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"string","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@string"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s12StaticStringV","text":"StaticString"},{"kind":"text","text":")"}]},"https://openusd.org/release/api/page_tf__diagnostic.html":{"titleInlineContent":[{"text":"OpenUSD documentation","type":"text"}],"type":"link","title":"OpenUSD documentation","identifier":"https:\/\/openusd.org\/release\/api\/page_tf__diagnostic.html","url":"https:\/\/openusd.org\/release\/api\/page_tf__diagnostic.html"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"anchor":"New-symbol-documentation","generated":true,"title":"New symbol documentation","identifiers":["doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/DereferencingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CreatingPointers","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/CheckingForValidity","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingEditContexts","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfNotice","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/WorkingWithTfErrorMark","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/UsingLibWork","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/ConvenientExtensions","doc:\/\/SwiftUsd\/documentation\/SwiftUsd\/TypeConversion"]}]}]}]}