{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IsValid","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"code":"IsValid","type":"codeVoice"},{"text":" will return true if this key refers to a currently active notification. Revoking the key will make it invalid again.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"title":"IsValid()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IsValid"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IsValid","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"}],"symbolKind":"method","externalID":"c:@N@pxr@S@TfNotice@S@SwiftKey@F@IsValid#1","modules":[{"name":"OpenUSD"}]},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/openusd\/swiftkey\/isvalid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/swiftkey\/isvalid"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Does this key refer to a valid notification?","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/IsValid"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://SwiftUsd/documentation/OpenUSD/SwiftKey":{"url":"\/documentation\/openusd\/swiftkey","title":"class SwiftKey","role":"symbol","abstract":[{"type":"text","text":"A key representing a listener registered from either Swift or C++"}],"type":"topic","navigatorTitle":[{"text":"SwiftKey","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SwiftKey","kind":"identifier"}],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/SwiftKey/IsValid":{"url":"\/documentation\/openusd\/swiftkey\/isvalid","title":"IsValid()","role":"symbol","abstract":[{"type":"text","text":"Does this key refer to a valid notification?"}],"type":"topic","navigatorTitle":[{"text":"IsValid","kind":"identifier"}],"identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/SwiftKey\/IsValid","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IsValid","kind":"identifier"},{"text":"()","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"}],"kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"IsValid"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"IsValid"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"IsValid","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"bool","kind":"typeIdentifier","preciseIdentifier":"c:b"},{"text":" ","kind":"text"},{"text":"IsValid","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"const","kind":"keyword"},{"text":";","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/title","op":"replace","value":"SwiftKey"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/fragments","op":"replace","value":[{"text":"SwiftKey","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey\/navigatorTitle","op":"replace","value":[{"text":"SwiftKey","kind":"identifier"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1IsValid\/title","op":"replace","value":"IsValid"},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1IsValid\/fragments","op":"replace","value":[{"kind":"identifier","text":"IsValid"}]},{"path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1SwiftKey~1IsValid\/navigatorTitle","op":"replace","value":[{"text":"IsValid","kind":"identifier"}]}]}]}