{"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateDefaultContextForAsset"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"assetPath"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@N@std","kind":"identifier","text":"std"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C","kind":"typeIdentifier","text":"string"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@N@pxr","kind":"identifier","text":"pxr"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@N@pxr@S@ArResolverContext","kind":"typeIdentifier","text":"ArResolverContext"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/openusd\/overlay\/arresolverwrapper\/createdefaultcontextforasset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/openusd\/overlay\/arresolverwrapper\/createdefaultcontextforasset"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateDefaultContextForAsset"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateDefaultContextForAsset","kind":"identifier"},{"text":"(","kind":"text"},{"text":"std","kind":"identifier","preciseIdentifier":"c:@N@std"},{"text":".","kind":"text"},{"text":"string","kind":"typeIdentifier","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"text":")","kind":"text"},{"text":" ","kind":"text"},{"text":"->","kind":"text"},{"text":" ","kind":"text"},{"text":"pxr","kind":"identifier","preciseIdentifier":"c:@N@pxr"},{"text":".","kind":"text"},{"text":"ArResolverContext","kind":"typeIdentifier","preciseIdentifier":"c:@N@pxr@S@ArResolverContext"}],"navigatorTitle":[{"kind":"identifier","text":"CreateDefaultContextForAsset"}],"title":"CreateDefaultContextForAsset(_:)","roleHeading":"Instance Method","role":"symbol","externalID":"c:@N@Overlay@S@ArResolverWrapper@F@CreateDefaultContextForAsset#&1$@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C#1","modules":[{"name":"OpenUSD"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/SwiftUsd\/documentation\/OpenUSD","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"references":{"doc://SwiftUsd/documentation/OpenUSD/Overlay":{"role":"symbol","abstract":[{"type":"text","text":"The namespace used to group workarounds to limitations in Swift-Cxx interop"}],"url":"\/documentation\/openusd\/overlay","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay","type":"topic","fragments":[{"text":"Overlay","kind":"identifier"}],"title":"Overlay","kind":"symbol"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper/CreateDefaultContextForAsset":{"url":"\/documentation\/openusd\/overlay\/arresolverwrapper\/createdefaultcontextforasset","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper\/CreateDefaultContextForAsset","title":"CreateDefaultContextForAsset(_:)","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"CreateDefaultContextForAsset"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreateDefaultContextForAsset"},{"kind":"text","text":"("},{"kind":"identifier","text":"std","preciseIdentifier":"c:@N@std"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"string","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C"},{"kind":"text","text":")"},{"kind":"text","text":" "},{"kind":"text","text":"->"},{"kind":"text","text":" "},{"kind":"identifier","text":"pxr","preciseIdentifier":"c:@N@pxr"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ArResolverContext","preciseIdentifier":"c:@N@pxr@S@ArResolverContext"}],"role":"symbol"},"doc://SwiftUsd/documentation/OpenUSD":{"title":"OpenUSD","url":"\/documentation\/openusd","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD","role":"collection"},"doc://SwiftUsd/documentation/OpenUSD/Overlay/ArResolverWrapper":{"abstract":[],"title":"class ArResolverWrapper","navigatorTitle":[{"kind":"identifier","text":"ArResolverWrapper"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftUsd\/documentation\/OpenUSD\/Overlay\/ArResolverWrapper","role":"symbol","url":"\/documentation\/openusd\/overlay\/arresolverwrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArResolverWrapper"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"CreateDefaultContextForAsset","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"CreateDefaultContextForAsset"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"CreateDefaultContextForAsset"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"text":"pxr","preciseIdentifier":"c:@N@pxr","kind":"identifier"},{"text":"::","kind":"text"},{"text":"ArResolverContext","preciseIdentifier":"c:@N@pxr@S@ArResolverContext","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"CreateDefaultContextForAsset","kind":"identifier"},{"text":"(","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"std","preciseIdentifier":"c:@N@std","kind":"identifier"},{"text":"::","kind":"text"},{"text":"string","preciseIdentifier":"c:@N@std@N@__1@S@basic_string>#C#$@N@std@N@__1@S@char_traits>#C#$@N@std@N@__1@S@allocator>#C","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"text":"assetPath","kind":"internalParam"},{"text":") ","kind":"text"},{"text":"const","kind":"keyword"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"Overlay","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/title"},{"value":[{"kind":"identifier","text":"Overlay"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/fragments"},{"value":[{"kind":"identifier","text":"Overlay"}],"op":"add","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay\/navigatorTitle"},{"value":"CreateDefaultContextForAsset","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateDefaultContextForAsset\/title"},{"value":[{"kind":"identifier","text":"CreateDefaultContextForAsset"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateDefaultContextForAsset\/fragments"},{"value":[{"text":"CreateDefaultContextForAsset","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper~1CreateDefaultContextForAsset\/navigatorTitle"},{"value":"ArResolverWrapper","op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/title"},{"value":[{"kind":"identifier","text":"ArResolverWrapper"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/fragments"},{"value":[{"text":"ArResolverWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1SwiftUsd~1documentation~1OpenUSD~1Overlay~1ArResolverWrapper\/navigatorTitle"}]}]}